# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-02 22:35
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=250)),
                ('tipo_ensenanza', models.CharField(choices=[('basica', 'Básica'), ('media', 'Media')], default='basica', max_length=250)),
                ('tipo_formacion', models.CharField(choices=[('general-dif.cient.human', 'Formación General y Diferenciada Humanístico-Científica'), ('general-dif.tec.profesional', 'Formación General y Diferenciada Técnico Profesional'), ('diferenciada-artistica', 'Formación Diferenciada Artística')], max_length=150)),
                ('niveles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('k', 'Kinder'), ('pk', 'Pre Kinder'), ('1', 'Primero Básico'), ('2', 'Segundo Básico'), ('3', 'Tercero Básico'), ('4', 'Cuarto Básico'), ('5', 'Quinto Básico'), ('6', 'Sexto Básico'), ('7', 'Septimo Básico'), ('8', 'Octavo Básico'), ('1M', 'Primero Medio'), ('2M', 'Segundo Medio'), ('3M', 'Tercero Medio'), ('4M', 'Cuarto Medio')], max_length=150), size=None)),
                ('lengua_indigena', models.BooleanField(default=False, verbose_name='¿Es Lengua Indigena?')),
                ('horas_anuales_jec', models.PositiveIntegerField(default=0, verbose_name='Horas anuales con JEC')),
                ('horas_anuales_sin_jec', models.PositiveIntegerField(default=0, verbose_name='Horas anuales sin JEC')),
                ('horas_semanales_jec', models.PositiveIntegerField(default=0, verbose_name='Horas semanales con JEC')),
                ('horas_semanales_sin_jec', models.PositiveIntegerField(default=0, verbose_name='Horas semanales sin JEC')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
            },
        ),
        migrations.CreateModel(
            name='AsignaturaExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=250)),
                ('horas_asignatura', models.PositiveIntegerField(null=True, verbose_name='Horas para la asignatura')),
                ('horas_asignadas', models.PositiveIntegerField(null=True, verbose_name='Horas asignadas a docentes')),
                ('horas_sin_asignar', models.PositiveIntegerField(null=True, verbose_name='Horas sin asignar')),
            ],
            options={
                'verbose_name': 'Asignatura extra',
                'verbose_name_plural': 'Asignaturas extra',
            },
        ),
        migrations.CreateModel(
            name='CargaHoraria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('horas_asignadas', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Carga horaria',
                'verbose_name_plural': 'Cargas horarias',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('tipo_ensenanza', models.CharField(choices=[('basica', 'Básica'), ('media', 'Media')], max_length=150, verbose_name='Tipo de enseñanza')),
                ('nivel', models.CharField(choices=[('k', 'Kinder'), ('pk', 'Pre Kinder'), ('1', 'Primero Básico'), ('2', 'Segundo Básico'), ('3', 'Tercero Básico'), ('4', 'Cuarto Básico'), ('5', 'Quinto Básico'), ('6', 'Sexto Básico'), ('7', 'Septimo Básico'), ('8', 'Octavo Básico'), ('1M', 'Primero Medio'), ('2M', 'Segundo Medio'), ('3M', 'Tercero Medio'), ('4M', 'Cuarto Medio')], max_length=150)),
                ('letra', models.CharField(max_length=10, null=True)),
                ('jornada', models.CharField(choices=[('media', 'Media Jornada'), ('completa', 'Jornada Completa')], max_length=150)),
                ('tipo_curso', models.CharField(choices=[('normal', 'Normal'), ('combinado', 'Combinado')], default='normal', max_length=150)),
                ('decreto_evaluacion', models.CharField(max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='DistribucionTiempoLectivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('jornada_semanal', models.PositiveIntegerField(verbose_name='Jornada Semanal (Horas cronológicas de contrato)')),
                ('horas_lectivas_HA', models.PositiveIntegerField(verbose_name='Horas lectivas (horas aula)')),
                ('horas_lectivas_HC', models.TimeField(verbose_name='Horas lectivas (horas cronológicas)')),
                ('recreo', models.TimeField()),
                ('horas_no_lectivas', models.TimeField(verbose_name='Horas no lectivas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('horas_asignatura', models.PositiveIntegerField(verbose_name='Horas para la asignatura')),
                ('horas_asignadas', models.PositiveIntegerField(verbose_name='Horas asignadas a docentes')),
                ('horas_sin_asignar', models.PositiveIntegerField(verbose_name='Horas sin asignar')),
            ],
            options={
                'verbose_name': 'Plan de Estudio',
                'verbose_name_plural': 'Planes de estudio',
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=250)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
            },
        ),
        migrations.CreateModel(
            name='TablaTiempoLectivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre de la tabla')),
                ('proporcion', models.CharField(max_length=150, verbose_name='Proporción')),
                ('decreto', models.CharField(max_length=250)),
                ('restriccion', models.CharField(max_length=250, verbose_name='Restricción de aplicación')),
            ],
            options={
                'verbose_name': 'Tabla de tiempo lectivo',
                'verbose_name_plural': 'Tablas de tiempo lectivo',
            },
        ),
    ]
