# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-02 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carga_horaria', '0001_initial'),
        ('gestion', '0001_initial'),
        ('recursos_humanos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestre',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Periodo'),
        ),
        migrations.AddField(
            model_name='planestudio',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga_horaria.Asignatura'),
        ),
        migrations.AddField(
            model_name='planestudio',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga_horaria.Curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='cursos',
            field=models.ManyToManyField(to='carga_horaria.Curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Periodo'),
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor_jefe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursos_humanos.FuncionarioColegio'),
        ),
        migrations.AddField(
            model_name='cargahoraria',
            name='asignatura_extra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carga_horaria.AsignaturaExtra'),
        ),
        migrations.AddField(
            model_name='cargahoraria',
            name='docente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursos_humanos.FuncionarioColegio'),
        ),
        migrations.AddField(
            model_name='cargahoraria',
            name='plan_estudio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carga_horaria.PlanEstudio'),
        ),
        migrations.AddField(
            model_name='asignaturaextra',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga_horaria.Curso'),
        ),
        migrations.AddField(
            model_name='asignaturaextra',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga_horaria.Semestre'),
        ),
    ]
