# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-05 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0002_auto_20200413_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='periodo',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
