# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-05 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0003_auto_20200505_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodo',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.RemoveField(
            model_name='plan',
            name='nombre',
        ),
    ]
