# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-06 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0004_auto_20200505_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
