# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-08 19:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0005_auto_20200506_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='horas',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(44)]),
        ),
    ]
