# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-08 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0006_auto_20200508_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='horas',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='horas',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='asignaturabase',
            name='horas_jec',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='asignaturabase',
            name='horas_nec',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
