# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-10 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0008_auto_20200508_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('horas', models.DecimalField(decimal_places=1, max_digits=3)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga_horaria.Profesor')),
            ],
        ),
    ]
