# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-10 23:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0009_asignacionextra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacionextra',
            old_name='item',
            new_name='descripcion',
        ),
    ]
