# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-12 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0010_auto_20200510_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionextra',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carga_horaria.Periodo'),
        ),
    ]
