# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-12 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0012_auto_20200512_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
