# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-14 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0013_asignatura_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='horas',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
