# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-28 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0016_auto_20200527_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='fundacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carga_horaria.Fundacion'),
        ),
    ]
