# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-17 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0017_profesor_fundacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carga_horaria.Periodo'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='tipo',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carga_horaria.Asignatura'),
        ),
    ]
