# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-03 13:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0019_asistente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistente',
            name='horas',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(45)]),
        ),
    ]
