# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-03 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0020_auto_20200703_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegio',
            name='ciudad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='colegio',
            name='comuna',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='colegio',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='colegio',
            name='financiamiento',
            field=models.PositiveSmallIntegerField(choices=[(1, 'particular pagado'), (2, 'financiamiento compartido'), (3, 'gratuito')], default=1),
        ),
        migrations.AddField(
            model_name='colegio',
            name='pie',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='colegio',
            name='rbd',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='colegio',
            name='telefono',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='colegio',
            name='web',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
