# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-13 20:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0021_auto_20200703_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='horas_no_aula',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(44)]),
        ),
    ]
