# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-22 16:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0023_asignacionnoaula'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegio',
            name='sep',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='horas',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(44)]),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='horas_no_aula',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(44)]),
        ),
    ]
