# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-22 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0024_auto_20200722_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carga_horaria.Especialidad', verbose_name='título'),
        ),
    ]
