# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-28 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0026_auto_20200722_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='colegio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carga_horaria.Colegio'),
        ),
    ]
