# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-28 18:11
from __future__ import unicode_literals

from django.db import migrations


def migrate_colegios(apps, schema_editor):
    Periodo = apps.get_model('carga_horaria', 'Periodo')

    for periodo in Periodo.objects.all():
        cc = periodo.colegio
        pp = periodo.plan
        pp.colegio = cc
        pp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0027_plan_colegio'),
    ]

    operations = [
        migrations.RunPython(migrate_colegios)
    ]
