# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-03 17:13
from __future__ import unicode_literals

from django.db import migrations

from django.contrib.postgres.operations import UnaccentExtension

class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0028_auto_20200728_1811'),
    ]

    operations = [
        UnaccentExtension()
    ]
