# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-03 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0029_auto_20200803_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionnoaula',
            name='tipo',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
