# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-11 15:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0030_asignacionnoaula_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistente',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='periodo',
            options={'ordering': ['plan'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['nivel'], 'verbose_name': 'Plan', 'verbose_name_plural': 'Planes'},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterField(
            model_name='periodo',
            name='horas_dif',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(22)]),
        ),
    ]
