# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-13 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0031_auto_20200811_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistente',
            name='colegio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carga_horaria.Colegio'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='colegio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carga_horaria.Colegio'),
        ),
    ]
