# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-28 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0033_auto_20200825_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegio',
            name='alumnos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='jec',
            field=models.BooleanField(default=True, verbose_name='JEC'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='pie',
            field=models.BooleanField(default=True, verbose_name='PIE'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='sep',
            field=models.BooleanField(default=True, verbose_name='SEP'),
        ),
    ]
