# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-28 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0034_auto_20200828_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='directivo',
            field=models.BooleanField(default=False),
        ),
    ]
