# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-31 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0036_periodo_horas_adicionales'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='profesor_jefe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carga_horaria.Profesor'),
        ),
    ]
