# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-09-03 12:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0037_periodo_profesor_jefe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='horas_dif',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
