# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-09-11 17:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0038_auto_20200903_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegio',
            name='prioritarios',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
