# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-09-11 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0042_auto_20200911_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='jec',
            field=models.BooleanField(default=True, verbose_name='JEC'),
        ),
    ]
