# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-09-23 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0043_periodo_jec'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='perioda',
            field=models.ManyToManyField(related_name='periodas', to='carga_horaria.Periodo'),
        ),
    ]
