# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-09-23 18:57
from __future__ import unicode_literals

from django.db import migrations


def forward(apps, schema_editor):
    Asignatura = apps.get_model("carga_horaria", "Asignatura")

    for aa in Asignatura.objects.all():
        periodo = aa.periodo
        aa.perioda.add(periodo)


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0044_asignatura_perioda'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
