# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-09-23 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0045_auto_20200923_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='periodo',
        ),
    ]
