# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-09-23 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0047_auto_20200923_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignatura',
            old_name='perioda',
            new_name='periodos',
        ),
    ]
