# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-09-28 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0048_auto_20200923_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='diferenciada',
            field=models.BooleanField(default=False),
        ),
    ]
