# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-09-29 14:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0049_asignatura_diferenciada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='horas',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.5)]),
        ),
    ]
