# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-10-07 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0051_profesor_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='horas_no_aula',
        ),
    ]
