# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-10-14 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0053_auto_20201014_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colegio',
            old_name='periodo',
            new_name='periode',
        ),
        migrations.AlterField(
            model_name='periodo',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga_horaria.Colegio'),
        ),
    ]
