# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-10-19 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0054_auto_20201014_2124'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='colegio',
            unique_together=set([('rbd', 'periode')]),
        ),
    ]
