# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-10-20 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0056_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carga_horaria.Persona'),
        ),
    ]
