# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-10-20 19:36
from __future__ import unicode_literals

from django.db import migrations


def migrate_profesores(apps, schema_editor):
    Profesor = apps.get_model('carga_horaria', 'Profesor')
    Persona = apps.get_model('carga_horaria', 'Persona')

    for profesor in Profesor.objects.all():
        obj, created = Persona.objects.get_or_create(
            rut=profesor.rut,
            defaults={'nombre': profesor.nombre,
                      'adventista': profesor.adventista})
        profesor.persona = obj
        profesor.save()


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0057_profesor_persona'),
    ]

    operations = [
        migrations.RunPython(migrate_profesores)
    ]
