# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-10-20 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0059_auto_20201020_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesor',
            options={},
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='adventista',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='rut',
        ),
    ]
