# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-10-20 19:47
from __future__ import unicode_literals

from django.db import migrations

def migrate_asistentes(apps, schema_editor):
    Asistente = apps.get_model('carga_horaria', 'Asistente')
    Persona = apps.get_model('carga_horaria', 'Persona')

    for asistente in Asistente.objects.all():
        obj, created = Persona.objects.get_or_create(
            rut=asistente.rut,
            defaults={'nombre': asistente.nombre,
                      'adventista': asistente.adventista})
        asistente.persona = obj
        asistente.save()


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0061_asistente_persona'),
    ]

    operations = [
        migrations.RunPython(migrate_asistentes)
    ]
