# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-10-20 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0062_auto_20201020_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistente',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga_horaria.Persona'),
        ),
    ]
