# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-10-20 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0063_auto_20201020_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistente',
            options={},
        ),
        migrations.RemoveField(
            model_name='asistente',
            name='adventista',
        ),
        migrations.RemoveField(
            model_name='asistente',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='asistente',
            name='rut',
        ),
    ]
