# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-10-30 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0064_auto_20201020_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(null=True, verbose_name='fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='cargo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Docente'), (2, 'Rector'), (3, 'Director'), (4, 'Subdirector'), (5, 'Inspector General'), (6, 'Jefe de UTP'), (7, 'Capellán'), (7, 'Administrador Financiero'), (7, 'Orientador')], default=1),
        ),
    ]
