# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-10-30 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0065_auto_20201030_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidad',
            options={'ordering': ('nombre',)},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'ordering': ('persona__nombre',)},
        ),
        migrations.AddField(
            model_name='profesor',
            name='observaciones',
            field=models.TextField(default=''),
        ),
    ]
