# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-11-06 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0066_auto_20201030_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='combinable',
            field=models.BooleanField(default=False),
        ),
    ]
