# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-11-13 14:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0068_auto_20201110_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='horas_indefinidas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(44)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='horas_plazo_fijo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(44)]),
            preserve_default=False,
        ),
    ]
