# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-11-16 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0070_auto_20201116_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegio',
            name='rbd',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
