# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-11-24 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0072_asignacionasistente_historicalasignacionasistente'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionasistente',
            name='tipo',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='historicalasignacionasistente',
            name='tipo',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
