# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-11-27 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0073_auto_20201124_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprofesor',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
    ]
