# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-12-17 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0074_auto_20201127_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofesor',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Indefinido'), (2, 'Plazo fijo'), (3, 'Reemplazo')], default=1, verbose_name='Tipo de contrato'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Indefinido'), (2, 'Plazo fijo'), (3, 'Reemplazo')], default=1, verbose_name='Tipo de contrato'),
        ),
    ]
