# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-12-30 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0076_auto_20201230_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprofesor',
            name='directivo',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='directivo',
        ),
    ]
