# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-01-14 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0077_auto_20201230_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='profesor_jefe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carga_horaria.Profesor'),
        ),
    ]
