# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-03-03 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0078_auto_20210114_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofesor',
            name='fecha_inicio',
            field=models.DateField(null=True, verbose_name='fecha inicio contrato'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='fecha_inicio',
            field=models.DateField(null=True, verbose_name='fecha inicio contrato'),
        ),
    ]
