# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-03-03 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0079_auto_20210303_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='direccion',
            field=models.CharField(default='', max_length=255, verbose_name='dirección'),
            preserve_default=False,
        ),
    ]
