# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-03-03 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0080_persona_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistente',
            name='fecha_inicio',
            field=models.DateField(null=True, verbose_name='fecha inicio contrato'),
        ),
        migrations.AddField(
            model_name='historicalasistente',
            name='fecha_inicio',
            field=models.DateField(null=True, verbose_name='fecha inicio contrato'),
        ),
    ]
