# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-03-11 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0081_auto_20210303_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='comuna',
            field=models.CharField(default='', max_length=255, verbose_name='comuna'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='discapacidad',
            field=models.BooleanField(default=False, verbose_name='discapacidad'),
        ),
        migrations.AddField(
            model_name='persona',
            name='email_institucional',
            field=models.EmailField(default='ejemplo@ejemplo.com', max_length=254, verbose_name='email institucional'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='email_personal',
            field=models.EmailField(default='ejemplo@ejemplo.com', max_length=254, verbose_name='email personal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='estado_civil',
            field=models.PositiveSmallIntegerField(choices=[(1, 'soltero(a)'), (2, 'casado(a)'), (3, 'separado(a)'), (4, 'divorciado(a)'), (5, 'viudo(a)')], default=1),
        ),
        migrations.AddField(
            model_name='persona',
            name='nacionalidad',
            field=models.CharField(default='Chilena', max_length=255, verbose_name='nacionalidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='recibe_pension',
            field=models.BooleanField(default=False, verbose_name='recibe pensión'),
        ),
        migrations.AddField(
            model_name='persona',
            name='telefono',
            field=models.CharField(default='0118 999 881 999 119 725 3', max_length=255, verbose_name='telefono'),
            preserve_default=False,
        ),
    ]
