# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-03-24 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0082_auto_20210311_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistente',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historicalasistente',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
    ]
