# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-07-05 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0086_auto_20210504_1555'),
        ('carga_horaria', '0086_auto_20210504_1545'),
    ]

    operations = [
    ]
