# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-07-05 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0087_merge_20210705_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprofesor',
            name='cargo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Docente'), (2, 'Rector'), (3, 'Director'), (4, 'Subdirector'), (5, 'Inspector General'), (6, 'Jefe de UTP'), (7, 'Capellán'), (8, 'Administrador Financiero'), (9, 'Orientador')], default=1),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='cargo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Docente'), (2, 'Rector'), (3, 'Director'), (4, 'Subdirector'), (5, 'Inspector General'), (6, 'Jefe de UTP'), (7, 'Capellán'), (8, 'Administrador Financiero'), (9, 'Orientador')], default=1),
        ),
    ]
