# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-08-04 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0088_auto_20210705_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegio',
            name='financiamiento',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Particular pagado'), (2, 'Financiamiento compartido'), (3, 'Gratuito')], default=1),
        ),
        migrations.AlterField(
            model_name='persona',
            name='estado_civil',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Soltero(a)'), (2, 'Casado(a)'), (3, 'Separado(a)'), (4, 'Divorciado(a)'), (5, 'Viudo(a)')], default=1),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(max_length=255, verbose_name='teléfono'),
        ),
    ]
