# Generated by Django 2.2 on 2021-08-30 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0089_auto_20210812_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carga_horaria.Asignatura'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carga_horaria.Periodo'),
        ),
        migrations.AlterField(
            model_name='asignacionasistente',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carga_horaria.Periodo'),
        ),
        migrations.AlterField(
            model_name='asignacionextra',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carga_horaria.Periodo'),
        ),
        migrations.AlterField(
            model_name='asignacionnoaula',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carga_horaria.Periodo'),
        ),
        migrations.AlterField(
            model_name='asistente',
            name='colegio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carga_horaria.Colegio'),
        ),
        migrations.AlterField(
            model_name='asistente',
            name='fundacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carga_horaria.Fundacion'),
        ),
        migrations.AlterField(
            model_name='historicalprofesor',
            name='especialidad',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga_horaria.Especialidad', verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='colegio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carga_horaria.Colegio'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carga_horaria.Especialidad', verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='fundacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carga_horaria.Fundacion'),
        ),
    ]
