# Generated by Django 2.2 on 2021-09-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0091_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegio',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='carga_horaria/colegio/logos/', verbose_name='Logo del Colegio'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploadedFile',
            field=models.FileField(upload_to='Uploaded Files/'),
        ),
    ]
