version: '3'

services:
  db:
    container_name: aagesuite_db
    image: postgres
    restart: always
    ports:
      - "5532:5432"
    env_file: .env
    volumes:
      - carga_db:/var/lib/postgresql/data

  web:  
    container_name: aagesuite
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    depends_on:
      - db

volumes:
  carga_db:
    external: true