# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-02 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('tipo_registro', models.CharField(max_length=150, verbose_name='Tipo de registro')),
                ('fecha', models.DateField()),
                ('horas', models.TimeField()),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
        migrations.CreateModel(
            name='Documentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('foto', models.FileField(upload_to='')),
                ('titulo', models.FileField(upload_to='', verbose_name='Título')),
                ('curriculum', models.FileField(upload_to='', verbose_name='Currículum')),
                ('certificado_antecedentes', models.FileField(upload_to='', verbose_name='Certificado de Antecedentes')),
            ],
            options={
                'verbose_name': 'Documentación',
                'verbose_name_plural': 'Documentación',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('rut', models.CharField(max_length=10)),
                ('nombres', models.CharField(max_length=250)),
                ('apellido_paterno', models.CharField(max_length=250)),
                ('apellido_materno', models.CharField(max_length=250)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=5, verbose_name='Género')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('nacionalidad', models.CharField(blank=True, max_length=150, null=True)),
                ('estado_civil', models.CharField(blank=True, choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('viudo', 'Viudo/a'), ('divorciado', 'Divorciado/a'), ('separado', 'Separado/a'), ('conviviente', 'Conviviente')], max_length=150, null=True)),
                ('religion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Religión')),
                ('direccion', models.CharField(max_length=500, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('antiguedad_docente_meses', models.PositiveIntegerField(verbose_name='Antiguedad del docente (en meses)')),
                ('fecha_ingreso_docente', models.DateField(verbose_name='Fecha de ingreso al Sistema Docente')),
                ('antiguedad_sea_meses', models.PositiveIntegerField(verbose_name='Antiguedad del funcionario en SEA (en meses)')),
                ('fecha_ingreso_sea', models.DateField(verbose_name='Fecha de ingreso al Sistema Educacional Adventista')),
                ('titulo', models.BooleanField(default=False, verbose_name='Título')),
                ('casa_formativa', models.CharField(max_length=1500)),
                ('profesion', models.CharField(max_length=1500, verbose_name='Profesión')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
            },
        ),
        migrations.CreateModel(
            name='FuncionarioColegio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('tipo_contrato', models.CharField(max_length=150, verbose_name='Tipo de contrato')),
                ('estado_funcionario', models.CharField(choices=[('contratado', 'Contratado'), ('desvinculado', 'Desvinculado')], default='contratado', max_length=150, verbose_name='Estado del funcionario')),
                ('funcion', models.CharField(max_length=250, verbose_name='Función')),
                ('sector_funcion', models.CharField(max_length=250, verbose_name='Sector de la función')),
                ('sub_sector_funcion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sub sector de la función')),
                ('funcion_secundaria', models.CharField(blank=True, max_length=250, null=True, verbose_name='Función secundaria')),
                ('sector_funcion_secundaria', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sector de la función secundaria')),
                ('sub_sector_funcion_secundaria', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sub sector de la función secundaria')),
                ('horas_contrato', models.PositiveIntegerField(verbose_name='Horas de contrato')),
                ('fecha_inicio_contrato', models.DateField(verbose_name='Fecha de inicio de contrato')),
                ('fecha_termino_contrato', models.DateField(blank=True, null=True, verbose_name='Fecha de término de contrato')),
                ('causa_termino_contrato', models.TextField(blank=True, max_length=2500, null=True, verbose_name='Causa de término de contrato')),
                ('colegio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.Colegio')),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursos_humanos.Funcionario')),
            ],
            options={
                'verbose_name': 'Funcionario de Colegio',
                'verbose_name_plural': 'Funcionarios de Colegios',
            },
        ),
        migrations.CreateModel(
            name='FuncionarioFundacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('tipo_contrato', models.CharField(max_length=150, verbose_name='Tipo de contrato')),
                ('estado_funcionario', models.CharField(choices=[('contratado', 'Contratado'), ('desvinculado', 'Desvinculado')], default='contratado', max_length=150, verbose_name='Estado del funcionario')),
                ('funcion', models.CharField(max_length=250, verbose_name='Función')),
                ('horas_contrato', models.PositiveIntegerField(verbose_name='Horas de contrato')),
                ('fecha_inicio_contrato', models.DateField(verbose_name='Fecha de inicio de contrato')),
                ('fecha_termino_contrato', models.DateField(blank=True, null=True, verbose_name='Fecha de termino de contrato')),
                ('causa_termino_contrato', models.TextField(blank=True, max_length=2500, null=True, verbose_name='Causa de termino de contrato')),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursos_humanos.Funcionario')),
                ('fundacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.Fundacion')),
            ],
            options={
                'verbose_name': 'Funcionario de Fundación',
                'verbose_name_plural': 'Funcionarios de Fundaciones',
            },
        ),
        migrations.CreateModel(
            name='FuncionarioUnion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('tipo_contrato', models.CharField(max_length=150, verbose_name='Tipo de contrato')),
                ('estado_funcionario', models.CharField(choices=[('contratado', 'Contratado'), ('desvinculado', 'Desvinculado')], default='contratado', max_length=150, verbose_name='Estado del funcionario')),
                ('funcion', models.CharField(max_length=250, verbose_name='Función')),
                ('horas_contrato', models.PositiveIntegerField(verbose_name='Horas de contrato')),
                ('fecha_inicio_contrato', models.DateField(verbose_name='Fecha de inicio de contrato')),
                ('fecha_termino_contrato', models.DateField(blank=True, null=True, verbose_name='Fecha de termino de contrato')),
                ('causa_termino_contrato', models.TextField(blank=True, max_length=2500, null=True, verbose_name='Causa de termino de contrato')),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursos_humanos.Funcionario')),
                ('union', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.Union')),
            ],
            options={
                'verbose_name': 'Funcionario de Unión',
                'verbose_name_plural': 'Funcionarios de Uniones',
            },
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('tipo_licencia', models.CharField(max_length=150, verbose_name='Tipo de licencia')),
                ('total_dias', models.PositiveIntegerField(verbose_name='Total de días')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_termino', models.DateField(verbose_name='Fecha de término')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_humanos.FuncionarioColegio')),
            ],
            options={
                'verbose_name': 'Licencia',
                'verbose_name_plural': 'Licencias',
            },
        ),
        migrations.CreateModel(
            name='ObservacionEntrevista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=150)),
                ('motivo', models.TextField(max_length=1250)),
                ('acuerdos', models.TextField(max_length=2500)),
                ('acta', models.FileField(upload_to='')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_humanos.FuncionarioColegio')),
                ('observador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observador', to='recursos_humanos.FuncionarioColegio')),
                ('observador_adjunto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursos_humanos.FuncionarioFundacion')),
            ],
            options={
                'verbose_name': 'Observación o entrevista',
                'verbose_name_plural': 'Observaciones o entrevistas',
            },
        ),
        migrations.CreateModel(
            name='ObservadorAdjunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('funcion', models.CharField(max_length=150, null=True)),
                ('observacion_entrevista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_humanos.ObservacionEntrevista')),
                ('observador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_humanos.FuncionarioColegio')),
            ],
            options={
                'verbose_name': 'Observador adjunto',
                'verbose_name_plural': 'Observadores adjuntos',
            },
        ),
        migrations.CreateModel(
            name='Perfeccionamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('tipo_perfeccionamiento', models.CharField(max_length=150)),
                ('perfeccionamiento', models.CharField(max_length=250)),
                ('institucion', models.CharField(max_length=250)),
                ('certificado', models.FileField(upload_to='')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_humanos.Funcionario')),
            ],
            options={
                'verbose_name': 'Perfeccionamiento',
                'verbose_name_plural': 'Perfeccionamientos',
            },
        ),
        migrations.CreateModel(
            name='Vacacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('total_dias', models.PositiveIntegerField(verbose_name='Total de días')),
                ('dias_pendientes', models.PositiveIntegerField(verbose_name='Días pendientes')),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('pendiente', models.BooleanField(default=False, verbose_name='¿Pertenece a vacaciones pendientes?')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_humanos.FuncionarioColegio')),
            ],
            options={
                'verbose_name': 'Vacación',
                'verbose_name_plural': 'Vacaciones',
            },
        ),
        migrations.AddField(
            model_name='documentacion',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_humanos.Funcionario'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_humanos.FuncionarioColegio'),
        ),
    ]
