# Generated by Django 2.2 on 2021-09-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipouniversoencuesta',
            name='codigo',
            field=models.CharField(choices=[('EN0002', 'Evaluación Personalizada')], max_length=10, verbose_name='Tipo de Configuración'),
        ),
    ]
