# Generated by Django 2.2 on 2021-09-27 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0003_auto_20210927_1549'),
        ('evado', '0002_auto_20210923_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universoencuesta',
            name='config_universo_persona',
        ),
        migrations.AddField(
            model_name='universoencuesta',
            name='evaluadores',
            field=models.ManyToManyField(to='rrhh.Persona', verbose_name='Evaluadores'),
        ),
        migrations.AddField(
            model_name='universoencuesta',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evado.PeriodoEncuesta'),
        ),
    ]
