# Generated by Django 2.2 on 2021-09-27 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evado', '0003_auto_20210927_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universoencuesta',
            name='tipo_encuesta',
        ),
    ]
