# Generated by Django 2.2 on 2021-09-27 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evado', '0004_remove_universoencuesta_tipo_encuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universoencuesta',
            name='periodo',
        ),
        migrations.AddField(
            model_name='universoencuesta',
            name='tipo_encuesta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evado.TipoUniversoEncuesta', verbose_name='Tipo de encuesta'),
            preserve_default=False,
        ),
    ]
