# Generated by Django 2.2 on 2021-09-27 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evado', '0006_universoencuesta_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicaruniversoencuestapersona',
            name='tipo_encuesta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evado.TipoUniversoEncuesta', verbose_name='Tipo de encuesta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='universoencuesta',
            name='tipo_encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evado.TipoUniversoEncuesta', verbose_name='Tipo de universo de encuesta'),
        ),
    ]
