# Generated by Django 2.2 on 2021-10-06 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evado', '0007_auto_20210927_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiporespuesta',
            name='encabezado',
            field=models.CharField(default=1, help_text='Este encabezado, aparecera en la encuesta como cabecera de las respuestas', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configurarencuestauniversopersona',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evado.PeriodoEncuesta', verbose_name='Grupo de encuesta'),
        ),
        migrations.AlterField(
            model_name='tiporespuesta',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='tipouniversoencuesta',
            name='codigo',
            field=models.CharField(choices=[('EN0000', 'Autoevaluación'), ('EN0001', 'Evaluación de Pares'), ('EN0002', 'Evaluación Personalizada'), ('EN0003', 'Evaluación desde Superiores')], max_length=10, verbose_name='Tipo de Configuración'),
        ),
        migrations.AlterField(
            model_name='universoencuesta',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evado.PeriodoEncuesta', verbose_name='Grupo de encuesta'),
        ),
        migrations.AlterField(
            model_name='universoencuesta',
            name='tipo_encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evado.TipoUniversoEncuesta', verbose_name='Tipo de encuesta'),
        ),
    ]
