# Generated by Django 2.2 on 2021-10-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evado', '0008_auto_20211006_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiporespuesta',
            name='encabezado',
            field=models.CharField(default='Escala de valoración', help_text='Este encabezado, aparecera en la encuesta como cabecera de las respuestas', max_length=150),
        ),
    ]
