from django.conf.urls import url
from . import views

app_name = 'rrhh'

urlpatterns = [
    url(r'^$', views.home, name='home_rrhh'),
    url(
        r'^uniones/$',
        views.UnionListView.as_view(),
        name='uniones'
    ),
    url(
        r'^uniones/nuevo/$',
        views.UnionCreateView.as_view(),
        name='union__nuevo'
    ),
    url(
        r'^uniones/(?P<pk>\d+)/$',
        views.UnionDetailView.as_view(),
        name='union'
    ),
    url(
        r'^uniones/(?P<pk>\d+)/editar/$',
        views.UnionUpdateView.as_view(),
        name='union__editar'
    ),
    url(
        r'^uniones/(?P<pk>\d+)/eliminar/$',
        views.UnionDeleteView.as_view(),
        name='union__eliminar'
    ),
    url(
        r'^fundaciones/$',
        views.FundacionListView.as_view(),
        name='fundaciones'
    ),
    url(
        r'^fundaciones/nuevo/$',
        views.FundacionCreateView.as_view(),
        name='fundacion__nuevo'
    ),
    url(
        r'^fundaciones/(?P<pk>\d+)/$',
        views.FundacionDetailView.as_view(),
        name='fundacion'
    ),
    url(
        r'^fundaciones/(?P<pk>\d+)/editar/$',
        views.FundacionUpdateView.as_view(),
        name='fundacion__editar'
    ),
    url(
        r'^fundaciones/(?P<pk>\d+)/eliminar/$',
        views.FundacionDeleteView.as_view(),
        name='fundacion__eliminar'
    ),
    url(
        r'^colegios/$',
        views.ColegioListView.as_view(),
        name='colegios'
    ),
    url(
        r'^colegios/nuevo/$',
        views.ColegioCreateView.as_view(),
        name='colegio__nuevo'
    ),
    url(
        r'^colegios/(?P<pk>\d+)/$',
        views.ColegioDetailView.as_view(),
        name='colegio'
    ),
    url(
        r'^colegios/(?P<pk>\d+)/editar/$',
        views.ColegioUpdateView.as_view(),
        name='colegio__editar'
    ),
    url(
        r'^colegios/(?P<pk>\d+)/eliminar/$',
        views.ColegioDeleteView.as_view(),
        name='colegio__eliminar'
    ),
    url(
        r'^personas/$',
        views.PersonaListView.as_view(),
        name='personas'
    ),
    url(
        r'^personas/nuevo/$',
        views.PersonaCreateView.as_view(),
        name='persona__nuevo'
    ),
    url(
        r'^personas/(?P<pk_persona>\d+)/$',
        views.persona_detail,
        name='persona'
    ),
    url(
        r'^personas/(?P<pk>\d+)/editar/$',
        views.PersonaUpdateView.as_view(),
        name='persona__editar'
    ),
    url(
        r'^personas/(?P<pk>\d+)/eliminar/$',
        views.PersonaDeleteView.as_view(),
        name='persona__eliminar'
    ),
    # url(
    #     r'^funcionarios/$',
    #     views.FuncionarioListView.as_view(),
    #     name='funcionarios'
    # ),
    url(
        r'^funcionarios/(?P<id_persona>\d+)/nuevo/$',
        views.crear_funcionario,
        name='funcionario__nuevo'
    ),
    # url(
    #     r'^funcionarios/(?P<pk>\d+)/$',
    #     views.FuncionarioDetailView.as_view(),
    #     name='funcionario'
    # ),
    url(
        r'^funcionarios/(?P<pk>\d+)/editar/$',
        views.FuncionarioUpdateView.as_view(),
        name='funcionario__editar'
    ),
    # url(
    #     r'^funcionarios/(?P<pk>\d+)/eliminar/$',
    #     views.FuncionarioDeleteView.as_view(),
    #     name='funcionario__eliminar'
    # ),
    url(
        r'^postulantes/$',
        views.postulantes,
        name='postulantes'
    ),
    url(
        r'^entrevistas/$',
        views.EntrevistaListView.as_view(),
        name='entrevistas'
    ),
    url(
        r'^entrevistas/nuevo/$',
        views.EntrevistaCreateView.as_view(),
        name='entrevista__nuevo'
    ),
    url(
        r'^entrevistas/(?P<pk>\d+)/$',
        views.EntrevistaDetailView.as_view(),
        name='entrevista'
    ),
    url(
        r'^entrevistas/nuevo/$',
        views.EntrevistaCreateView.as_view(),
        name='entrevista__nuevo'
    ),
    url(
        r'^entrevistas/(?P<pk>\d+)/editar/$',
        views.EntrevistaUpdateView.as_view(),
        name='entrevista__editar'
    ),
    url(
        r'^entrevistas/(?P<pk>\d+)/eliminar/$',
        views.EntrevistaDeleteView.as_view(),
        name='entrevista__eliminar'
    ),
    url(
        r'^documentos/$',
        views.DocumentoFuncionarioListView.as_view(),
        name='documentos'
    ),
    url(
        r'^documentos/nuevo/$',
        views.DocumentoFuncionarioCreateView.as_view(),
        name='documento__nuevo'
    ),
    url(
        r'^documentos/(?P<pk>\d+)/$',
        views.DocumentoFuncionarioDetailView.as_view(),
        name='documento'
    ),
    url(
        r'^documentos/nuevo/$',
        views.DocumentoFuncionarioCreateView.as_view(),
        name='documento__nuevo'
    ),
    url(
        r'^documentos/(?P<pk>\d+)/editar/$',
        views.DocumentoFuncionarioUpdateView.as_view(),
        name='documento__editar'
    ),
    url(
        r'^documentos/(?P<pk>\d+)/eliminar/$',
        views.DocumentoFuncionarioDeleteView.as_view(),
        name='documento__eliminar'
    ),
    url(
        r'^vacaciones/$',
        views.VacacionListView.as_view(),
        name='vacaciones'
    ),
    url(
        r'^vacaciones/nuevo/$',
        views.VacacionCreateView.as_view(),
        name='vacacion__nuevo'
    ),
    url(
        r'^vacaciones/(?P<pk>\d+)/$',
        views.VacacionDetailView.as_view(),
        name='vacacion'
    ),
    url(
        r'^vacaciones/(?P<pk>\d+)/editar/$',
        views.VacacionUpdateView.as_view(),
        name='vacacion__editar'
    ),
    url(
        r'^vacaciones/(?P<pk>\d+)/eliminar/$',
        views.VacacionDeleteView.as_view(),
        name='vacacion__eliminar'
    ),
    url(
        r'^tiposlicencia/$',
        views.TipoLicenciaListView.as_view(),
        name='tiposlicencia'
    ),
    url(
        r'^tiposlicencia/nuevo/$',
        views.TipoLicenciaCreateView.as_view(),
        name='tipolicencia__nuevo'
    ),
    url(
        r'^tiposlicencia/(?P<pk>\d+)/$',
        views.TipoLicenciaDetailView.as_view(),
        name='tipolicencia'
    ),
    url(
        r'^tiposlicencia/(?P<pk>\d+)/editar/$',
        views.TipoLicenciaUpdateView.as_view(),
        name='tipolicencia__editar'
    ),
    url(
        r'^tiposlicencia/(?P<pk>\d+)/eliminar/$',
        views.TipoLicenciaDeleteView.as_view(),
        name='tipolicencia__eliminar'
    ),
    url(
        r'^licencias/$',
        views.LicenciaListView.as_view(),
        name='licencias'
    ),
    url(
        r'^licencias/nuevo/$',
        views.LicenciaCreateView.as_view(),
        name='licencia__nuevo'
    ),
    url(
        r'^licencias/(?P<pk>\d+)/$',
        views.LicenciaDetailView.as_view(),
        name='licencia'
    ),
    url(
        r'^licencias/(?P<pk>\d+)/editar/$',
        views.LicenciaUpdateView.as_view(),
        name='licencia__editar'
    ),
    url(
        r'^licencias/(?P<pk>\d+)/eliminar/$',
        views.LicenciaDeleteView.as_view(),
        name='licencia__eliminar'
    ),
    url(
        r'^licencias_funcionario/nuevo/$',
        views.nuevo_licencia_tipo_funcionario,
        name='licencia_funcionario__nuevo'
    ),
    url(
        r'^vacaciones_funcionario/nuevo/$',
        views.nuevo_vacacion_funcionario,
        name='vacacion_funcionario__nuevo'
    ),
    url(
        r'^contratos/nuevo/(?P<id_funcionario>\d+)/(?P<id_solicitud>\d+)/',
        views.crear_contrato_colegio,
        name='contrato_colegio__crear'
    ),
    url(
        r'^contratos/$',
        views.ContratoListView.as_view(),
        name='contratos'
    ),
    url(
        r'^contratos/nuevo/$',
        views.ContratoCreateView.as_view(),
        name='contrato__nuevo'
    ),
    url(
        r'^contratos/(?P<pk>\d+)/$',
        views.ContratoDetailView.as_view(),
        name='contrato'
    ),
    url(
        r'^contratos/(?P<pk>\d+)/editar/$',
        views.ContratoUpdateView.as_view(),
        name='contrato__editar'
    ),
    url(
        r'^contratos/(?P<pk>\d+)/eliminar/$',
        views.ContratoDeleteView.as_view(),
        name='contrato__eliminar'
    ),
    url(
        r'^funciones/$',
        views.FuncionListView.as_view(),
        name='funciones'
    ),
    url(
        r'^funciones/nuevo/$',
        views.FuncionCreateView.as_view(),
        name='funcion__nuevo'
    ),
    url(
        r'^funciones/(?P<pk>\d+)/$',
        views.FuncionDetailView.as_view(),
        name='funcion'
    ),
    url(
        r'^funciones/(?P<pk>\d+)/editar/$',
        views.FuncionUpdateView.as_view(),
        name='funcion__editar'
    ),
    url(
        r'^funciones/(?P<pk>\d+)/eliminar/$',
        views.FuncionDeleteView.as_view(),
        name='funcion__eliminar'
    ),
    url(
        r'^afps/$',
        views.AFPListView.as_view(),
        name='afps'
    ),
    url(
        r'^afps/nuevo/$',
        views.AFPCreateView.as_view(),
        name='afp__nuevo'
    ),
    url(
        r'^afps/(?P<pk>\d+)/$',
        views.AFPDetailView.as_view(),
        name='afp'
    ),
    url(
        r'^afps/(?P<pk>\d+)/editar/$',
        views.AFPUpdateView.as_view(),
        name='afp__editar'
    ),
    url(
        r'^afps/(?P<pk>\d+)/eliminar/$',
        views.AFPDeleteView.as_view(),
        name='afp__eliminar'
    ),
    url(
        r'^isapres/$',
        views.IsapreListView.as_view(),
        name='isapres'
    ),
    url(
        r'^isapres/nuevo/$',
        views.IsapreCreateView.as_view(),
        name='isapre__nuevo'
    ),
    url(
        r'^isapres/(?P<pk>\d+)/$',
        views.IsapreDetailView.as_view(),
        name='isapre'
    ),
    url(
        r'^isapres/(?P<pk>\d+)/editar/$',
        views.IsapreUpdateView.as_view(),
        name='isapre__editar'
    ),
    url(
        r'^isapres/(?P<pk>\d+)/eliminar/$',
        views.IsapreDeleteView.as_view(),
        name='isapre__eliminar'
    ),
    url(
        r'^finiquito/(?P<id_contrato>\d+)/$',
        views.nuevo_finiquito,
        name='finiquito__nuevo'
    ),
    url(
        r'^finiquitos/(?P<pk>\d+)/eliminar/$',
        views.FiniquitoDeleteView.as_view(),
        name='finiquito__eliminar'
    ),
    url(
        r'^solicitudes/$',
        views.SolicitudContratacionListView.as_view(),
        name='solicitudes'
    ),
    url(
        r'^solicitudes/nuevo/$',
        views.SolicitudContratacionCreateView.as_view(),
        name='solicitud__nuevo'
    ),
    url(
        r'^solicitudes/(?P<pk>\d+)/$',
        views.SolicitudContratacionDetailView.as_view(),
        name='solicitud'
    ),
    url(
        r'^solicitudes/(?P<pk>\d+)/editar/$',
        views.SolicitudContratacionUpdateView.as_view(),
        name='solicitud__editar'
    ),
    url(
        r'^solicitudes/(?P<pk>\d+)/eliminar/$',
        views.SolicitudContratacionDeleteView.as_view(),
        name='solicitud__eliminar'
    ),
    url(
        r'^estado-solicitud/cambiar/$',
        views.cambiar_estado_solicitud,
        name='estado_solicitud__cambiar'
    ),
    url(
        r'^solicitudes/(?P<id_solicitud>\d+)/seleccionar_cadidatos/$',
        views.seleccionar_candidatos,
        name='candidatos__seleccionar'
    ),
    url(
        r'^solicitudes/guardar_candidato/$',
        views.guardar_candidato,
        name='candidatos__guardar'
    ),
    url(
        r'^contratos/(?P<id_contrato>\d+)/renovar/$',
        views.renovar_contrato,
        name='contrato__renovar'
    ),
    url(
        r'^funcionario/(?P<id_contrato>\d+)/trasladar/$',
        views.trasladar_funcionario,
        name='funcionario__trasladar'
    ),
    url(
        r'^contratos/(?P<id_contrato>\d+)/renovacion/contratar/$',
        views.renovar_contrato_colegio,
        name='renovacion_contrato__contratar'
    ),
]
