from django.conf.urls import url
from . import views

app_name = 'rrhh'

urlpatterns = [
    url(r'^$', views.home, name='home_rrhh'),
    url(
        r'^pesonas/$',
        views.PersonaListView.as_view(),
        name='personas'
    ),
    url(
        r'^personas/nuevo/$',
        views.PersonaCreateView.as_view(),
        name='persona__nuevo'
    ),
    url(
        r'^personas/(?P<pk_persona>\d+)/$',
        views.persona_detail,
        name='persona'
    ),
    url(
        r'^personas/(?P<pk>\d+)/editar/$',
        views.PersonaUpdateView.as_view(),
        name='persona__editar'
    ),
    url(
        r'^personas/(?P<pk>\d+)/eliminar/$',
        views.PersonaDeleteView.as_view(),
        name='persona__eliminar'
    ),
    url(
        r'^entrevistas/$',
        views.EntrevistaListView.as_view(),
        name='entrevistas'
    ),
    url(
        r'^entrevistas/nuevo/$',
        views.EntrevistaCreateView.as_view(),
        name='entrevista__nuevo'
    ),
    url(
        r'^entrevistas/(?P<pk>\d+)/$',
        views.EntrevistaDetailView.as_view(),
        name='entrevista'
    ),
    url(
        r'^entrevistas/nuevo/$',
        views.EntrevistaCreateView.as_view(),
        name='entrevista__nuevo'
    ),
    url(
        r'^entrevistas/(?P<pk>\d+)/editar/$',
        views.EntrevistaUpdateView.as_view(),
        name='entrevista__editar'
    ),
    url(
        r'^entrevistas/(?P<pk>\d+)/eliminar/$',
        views.EntrevistaDeleteView.as_view(),
        name='entrevista__eliminar'
    ),
    url(
        r'^archivos/$',
        views.ArchivoListView.as_view(),
        name='archivos'
    ),
    url(
        r'^archivos/nuevo/$',
        views.ArchivoCreateView.as_view(),
        name='archivo__nuevo'
    ),
    url(
        r'^archivos/(?P<pk>\d+)/$',
        views.ArchivoDetailView.as_view(),
        name='archivo'
    ),
    url(
        r'^archivos/nuevo/$',
        views.ArchivoCreateView.as_view(),
        name='archivo__nuevo'
    ),
    url(
        r'^archivos/(?P<pk>\d+)/editar/$',
        views.ArchivoUpdateView.as_view(),
        name='archivo__editar'
    ),
    url(
        r'^archivos/(?P<pk>\d+)/eliminar/$',
        views.ArchivoDeleteView.as_view(),
        name='archivo__eliminar'
    ),
    url(
        r'^vacaciones/$',
        views.VacacionListView.as_view(),
        name='vacaciones'
    ),
    url(
        r'^vacaciones/nuevo/$',
        views.VacacionCreateView.as_view(),
        name='vacacion__nuevo'
    ),
    url(
        r'^vacaciones/(?P<pk>\d+)/$',
        views.VacacionDetailView.as_view(),
        name='vacacion'
    ),
    url(
        r'^vacaciones/(?P<pk>\d+)/editar/$',
        views.VacacionUpdateView.as_view(),
        name='vacacion__editar'
    ),
    url(
        r'^vacaciones/(?P<pk>\d+)/eliminar/$',
        views.VacacionDeleteView.as_view(),
        name='vacacion__eliminar'
    ),
    url(
        r'^tiposlicencia/$',
        views.TipoLicenciaListView.as_view(),
        name='tiposlicencia'
    ),
    url(
        r'^tiposlicencia/nuevo/$',
        views.TipoLicenciaCreateView.as_view(),
        name='tipolicencia__nuevo'
    ),
    url(
        r'^tiposlicencia/(?P<pk>\d+)/$',
        views.TipoLicenciaDetailView.as_view(),
        name='tipolicencia'
    ),
    url(
        r'^tiposlicencia/(?P<pk>\d+)/editar/$',
        views.TipoLicenciaUpdateView.as_view(),
        name='tipolicencia__editar'
    ),
    url(
        r'^tiposlicencia/(?P<pk>\d+)/eliminar/$',
        views.TipoLicenciaDeleteView.as_view(),
        name='tipolicencia__eliminar'
    ),
    url(
        r'^licencias/$',
        views.LicenciaListView.as_view(),
        name='licencias'
    ),
    url(
        r'^licencias/nuevo/$',
        views.LicenciaCreateView.as_view(),
        name='licencia__nuevo'
    ),
    url(
        r'^licencias/(?P<pk>\d+)/$',
        views.LicenciaDetailView.as_view(),
        name='licencia'
    ),
    url(
        r'^licencias/(?P<pk>\d+)/editar/$',
        views.LicenciaUpdateView.as_view(),
        name='licencia__editar'
    ),
    url(
        r'^licencias/(?P<pk>\d+)/eliminar/$',
        views.LicenciaDeleteView.as_view(),
        name='licencia__eliminar'
    ),
    url(
        r'^licencias_funcionario/nuevo/$',
        views.nuevo_licencia_tipo_funcionario,
        name='licencia_funcionario__nuevo'
    ),
    url(
        r'^vacaciones_funcionario/nuevo/$',
        views.nuevo_vacacion_funcionario,
        name='vacacion_funcionario__nuevo'
    ),
    url(
        r'^contratos/$',
        views.ContratoListView.as_view(),
        name='contratos'
    ),
    url(
        r'^contratos/nuevo/$',
        views.ContratoCreateView.as_view(),
        name='contrato__nuevo'
    ),
    url(
        r'^contratos/(?P<pk>\d+)/$',
        views.ContratoDetailView.as_view(),
        name='contrato'
    ),
    url(
        r'^contratos/(?P<pk>\d+)/editar/$',
        views.ContratoUpdateView.as_view(),
        name='contrato__editar'
    ),
    url(
        r'^contratos/(?P<pk>\d+)/eliminar/$',
        views.ContratoDeleteView.as_view(),
        name='contrato__eliminar'
    ),
    url(
        r'^funciones/$',
        views.FuncionListView.as_view(),
        name='funciones'
    ),
    url(
        r'^funciones/nuevo/$',
        views.FuncionCreateView.as_view(),
        name='funcion__nuevo'
    ),
    url(
        r'^funciones/(?P<pk>\d+)/$',
        views.FuncionDetailView.as_view(),
        name='funcion'
    ),
    url(
        r'^funciones/(?P<pk>\d+)/editar/$',
        views.FuncionUpdateView.as_view(),
        name='funcion__editar'
    ),
    url(
        r'^funciones/(?P<pk>\d+)/eliminar/$',
        views.FuncionDeleteView.as_view(),
        name='funcion__eliminar'
    ),
    url(
        r'^afps/$',
        views.AFPListView.as_view(),
        name='afps'
    ),
    url(
        r'^afps/nuevo/$',
        views.AFPCreateView.as_view(),
        name='afp__nuevo'
    ),
    url(
        r'^afps/(?P<pk>\d+)/$',
        views.AFPDetailView.as_view(),
        name='afp'
    ),
    url(
        r'^afps/(?P<pk>\d+)/editar/$',
        views.AFPUpdateView.as_view(),
        name='afp__editar'
    ),
    url(
        r'^afps/(?P<pk>\d+)/eliminar/$',
        views.AFPDeleteView.as_view(),
        name='afp__eliminar'
    ),
    url(
        r'^isapres/$',
        views.IsapreListView.as_view(),
        name='isapres'
    ),
    url(
        r'^isapres/nuevo/$',
        views.IsapreCreateView.as_view(),
        name='isapre__nuevo'
    ),
    url(
        r'^isapres/(?P<pk>\d+)/$',
        views.IsapreDetailView.as_view(),
        name='isapre'
    ),
    url(
        r'^isapres/(?P<pk>\d+)/editar/$',
        views.IsapreUpdateView.as_view(),
        name='isapre__editar'
    ),
    url(
        r'^isapres/(?P<pk>\d+)/eliminar/$',
        views.IsapreDeleteView.as_view(),
        name='isapre__eliminar'
    ),
    url(
        r'^finiquito/(?P<id_contrato>\d+)/$',
        views.nuevo_finiquito,
        name='finiquito__nuevo'
    ),
    url(
        r'^finiquitos/(?P<pk>\d+)/eliminar/$',
        views.FiniquitoDeleteView.as_view(),
        name='finiquito__eliminar'
    ),
]
