from django.conf.urls import url
from . import views

app_name = 'rrhh'

urlpatterns = [
    url(r'^$', views.home, name='home_rrhh'),
    url(
        r'^funcionarios/$',
        views.FuncionarioListView.as_view(),
        name='funcionarios'
    ),
    url(
        r'^funcionarios/nuevo/$',
        views.FuncionarioCreateView.as_view(),
        name='funcionario__nuevo'
    ),
    url(
        r'^funcionarios/(?P<pk>\d+)/$',
        views.FuncionarioDetailView.as_view(),
        name='funcionario'
    ),
    url(
        r'^funcionarios/(?P<pk>\d+)/editar/$',
        views.FuncionarioUpdateView.as_view(),
        name='funcionario__editar'
    ),
    url(
        r'^funcionarios/(?P<pk>\d+)/eliminar/$',
        views.FuncionarioDeleteView.as_view(),
        name='funcionario__eliminar'
    ),
    url(
        r'^entrevistas/$',
        views.EntrevistaListView.as_view(),
        name='entrevistas'
    ),
    url(
        r'^entrevistas/nuevo/$',
        views.EntrevistaCreateView.as_view(),
        name='entrevista__nuevo'
    ),
    url(
        r'^entrevistas/(?P<pk>\d+)/$',
        views.EntrevistaDetailView.as_view(),
        name='entrevista'
    ),
    url(
        r'^entrevistas/nuevo/$',
        views.EntrevistaCreateView.as_view(),
        name='entrevista__nuevo'
    ),
    url(
        r'^entrevistas/(?P<pk>\d+)/editar/$',
        views.EntrevistaUpdateView.as_view(),
        name='entrevista__editar'
    ),
    url(
        r'^entrevistas/(?P<pk>\d+)/eliminar/$',
        views.EntrevistaDeleteView.as_view(),
        name='entrevista__eliminar'
    ),
    url(
        r'^archivos/$',
        views.ArchivoListView.as_view(),
        name='archivos'
    ),
    url(
        r'^archivos/nuevo/$',
        views.ArchivoCreateView.as_view(),
        name='archivo__nuevo'
    ),
    url(
        r'^archivos/(?P<pk>\d+)/$',
        views.ArchivoDetailView.as_view(),
        name='archivo'
    ),
    url(
        r'^archivos/nuevo/$',
        views.ArchivoCreateView.as_view(),
        name='archivo__nuevo'
    ),
    url(
        r'^archivos/(?P<pk>\d+)/editar/$',
        views.ArchivoUpdateView.as_view(),
        name='archivo__editar'
    ),
    url(
        r'^archivos/(?P<pk>\d+)/eliminar/$',
        views.ArchivoDeleteView.as_view(),
        name='archivo__eliminar'
    ),
    url(
        r'^vacaciones/$',
        views.VacacionListView.as_view(),
        name='vacaciones'
    ),
    url(
        r'^vacaciones/nuevo/$',
        views.VacacionCreateView.as_view(),
        name='vacacion__nuevo'
    ),
    url(
        r'^vacaciones/(?P<pk>\d+)/$',
        views.VacacionDetailView.as_view(),
        name='vacacion'
    ),
    url(
        r'^vacaciones/(?P<pk>\d+)/editar/$',
        views.VacacionUpdateView.as_view(),
        name='vacacion__editar'
    ),
    url(
        r'^vacaciones/(?P<pk>\d+)/eliminar/$',
        views.VacacionDeleteView.as_view(),
        name='vacacion__eliminar'
    ),
    url(
        r'^tiposlicencia/$',
        views.TipoLicenciaListView.as_view(),
        name='tiposlicencia'
    ),
    url(
        r'^tiposlicencia/nuevo/$',
        views.TipoLicenciaCreateView.as_view(),
        name='tipolicencia__nuevo'
    ),
    url(
        r'^tiposlicencia/(?P<pk>\d+)/$',
        views.TipoLicenciaDetailView.as_view(),
        name='tipolicencia'
    ),
    url(
        r'^tiposlicencia/(?P<pk>\d+)/editar/$',
        views.TipoLicenciaUpdateView.as_view(),
        name='tipolicencia__editar'
    ),
    url(
        r'^tiposlicencia/(?P<pk>\d+)/eliminar/$',
        views.TipoLicenciaDeleteView.as_view(),
        name='tipolicencia__eliminar'
    ),
    url(
        r'^licencias/$',
        views.LicenciaListView.as_view(),
        name='licencias'
    ),
    url(
        r'^licencias/nuevo/$',
        views.LicenciaCreateView.as_view(),
        name='licencia__nuevo'
    ),
    url(
        r'^licencias/(?P<pk>\d+)/$',
        views.LicenciaDetailView.as_view(),
        name='licencia'
    ),
    url(
        r'^licencias/(?P<pk>\d+)/editar/$',
        views.LicenciaUpdateView.as_view(),
        name='licencia__editar'
    ),
    url(
        r'^licencias/(?P<pk>\d+)/eliminar/$',
        views.LicenciaDeleteView.as_view(),
        name='licencia__eliminar'
    ),
]
