# Generated by Django 2.2 on 2021-09-21 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AFP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField(max_length=2500, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'AFP',
                'verbose_name_plural': 'AFPs',
            },
        ),
        migrations.CreateModel(
            name='AreaTitulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField(max_length=2500, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Área de título',
                'verbose_name_plural': 'Areas de titulos',
            },
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField(max_length=2500, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.PositiveSmallIntegerField(choices=[(1, 'Docente Directivo'), (2, 'Docente'), (3, 'Asistente de Educación'), (4, 'Otro Profesional')], verbose_name='Categoría')),
                ('tipo_contrato', models.PositiveSmallIntegerField(choices=[(1, 'Indefinido'), (2, 'A plazo'), (3, 'Reemplazo')], default=1, verbose_name='Tipo de contrato')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_termino', models.DateField(blank=True, null=True, verbose_name='Fecha de Término')),
                ('horas_total', models.PositiveIntegerField(verbose_name='Horas contratadas')),
                ('sueldo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sueldo a percibir')),
                ('asignacion_funcion', models.PositiveIntegerField(blank=True, null=True, verbose_name='Asignación por función')),
                ('asignacion_locomocion', models.PositiveIntegerField(blank=True, null=True, verbose_name='Asignación por locomoción')),
                ('vigente', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('abrev', models.CharField(max_length=50, verbose_name='Abreviación')),
                ('direccion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Dirección')),
                ('tipo_entidad', models.CharField(choices=[('colegio', 'Colegio'), ('fundacion', 'Fundación'), ('union', 'Unión')], default='colegio', max_length=50)),
                ('dependiente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.Entidad', verbose_name='Depende de')),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField(max_length=2500, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField(max_length=2500, verbose_name='Descripción')),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'Funcion principal'), (2, 'Función secundaria')], default=1, verbose_name='Tipo de función')),
            ],
            options={
                'verbose_name': 'Función de empleado',
                'verbose_name_plural': 'Funciones de empleados',
            },
        ),
        migrations.CreateModel(
            name='Isapre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField(max_length=2500, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Isapre',
                'verbose_name_plural': 'Isapres',
            },
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_licencia_descripcion', models.TextField(blank=True, max_length=500, null=True, verbose_name='Tipo de licencia')),
                ('folio_licencia', models.CharField(blank=True, max_length=30, null=True, verbose_name='Folio de la licencia')),
                ('total_dias', models.IntegerField(verbose_name='Total de días de licencia')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('total_feriados', models.IntegerField(default=0, verbose_name='Total de feriados en el periodo de la licencia')),
                ('fecha_termino', models.DateField(blank=True, null=True, verbose_name='Fecha de término')),
                ('fecha_retorno', models.DateField(blank=True, null=True, verbose_name='Fecha de retorno')),
                ('dias_habiles', models.BooleanField(default=True, verbose_name='Corresponde a días hábiles')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Contrato')),
            ],
            options={
                'verbose_name': 'Licencia',
                'verbose_name_plural': 'Licencias',
            },
        ),
        migrations.CreateModel(
            name='Mencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField(max_length=2500, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Mención',
                'verbose_name_plural': 'Menciones',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_perfil', models.PositiveSmallIntegerField(choices=[(1, 'Docente'), (2, 'Capellán'), (3, 'Jefe de UTP'), (4, 'Inspector General'), (5, 'Director'), (6, 'Departamental'), (7, 'Asesor'), (8, 'Administrador')], default=1, verbose_name='Tipo de perfil')),
                ('descripcion', models.TextField(blank=True, max_length=550, null=True, verbose_name='Descripción')),
                ('solo_lectura', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_dias', models.IntegerField(verbose_name='Total de días de permiso')),
                ('observaciones', models.TextField(max_length=2500, verbose_name='Motivos u observaciones')),
                ('fecha_solicitud', models.DateField(verbose_name='Fecha de solicitud')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('total_feriados', models.IntegerField(default=0, verbose_name='Total de feriados en el periodo del permiso')),
                ('fecha_termino', models.DateField(blank=True, null=True, verbose_name='Fecha de término')),
                ('fecha_retorno', models.DateField(blank=True, null=True, verbose_name='Fecha de retorno')),
                ('goce_sueldo', models.BooleanField(default=False, verbose_name='Con goce de sueldo')),
                ('dias_habiles', models.BooleanField(default=True, verbose_name='Corresponde a días hábiles')),
                ('voto', models.PositiveIntegerField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Contrato')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=16, unique=True)),
                ('nombres', models.CharField(max_length=255)),
                ('apellido_paterno', models.CharField(max_length=255)),
                ('apellido_materno', models.CharField(max_length=255)),
                ('genero', models.CharField(blank=True, choices=[('femenino', 'Femenino'), ('masculino', 'Masculino')], default='masculino', max_length=100, null=True, verbose_name='Género')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('nacionalidad', models.CharField(choices=[('chilena', 'Chilena'), ('extranjera', 'Extranjera')], default='chilena', max_length=100)),
                ('estado_civil', models.CharField(choices=[('soltero', 'Soltero'), ('casado', 'Casado'), ('divorsiado', 'Divorsiado'), ('viudo', 'Viudo')], default='soltero', max_length=100)),
                ('religion', models.BooleanField(default=True, verbose_name='Adventista del Séptimo día')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('telefono', models.PositiveIntegerField(blank=True, help_text='Número de 9 dígitos', null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('titulado', models.BooleanField(default=False)),
                ('profesion', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Título profesional')),
                ('foto', models.FileField(blank=True, null=True, upload_to='rrhh/fotos', verbose_name='Foto de perfil')),
                ('curriculum', models.FileField(blank=True, null=True, upload_to='rrhh/curriculums')),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.Ciudad')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('numero', models.PositiveSmallIntegerField(default=0)),
                ('numero_romano', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField(max_length=2500, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documento',
            },
        ),
        migrations.CreateModel(
            name='TipoLicencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField(max_length=2500, verbose_name='Descripción')),
                ('total_dias', models.IntegerField(verbose_name='Total de días correspondientes')),
                ('dias_habiles', models.BooleanField(default=True, verbose_name='Corresponde a días hábiles')),
            ],
            options={
                'verbose_name': 'Tipo de licencia',
                'verbose_name_plural': 'Tipos de licencia',
            },
        ),
        migrations.CreateModel(
            name='TipoTitulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField(max_length=2500, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de título',
                'verbose_name_plural': 'Tipos ded titulos',
            },
        ),
        migrations.CreateModel(
            name='Vacacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_vacacion', models.PositiveIntegerField(default=0)),
                ('total_dias', models.IntegerField(verbose_name='Total de días de vacaciones')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('total_feriados', models.IntegerField(default=0, verbose_name='Total de feriados en el periodo de vacaciones')),
                ('fecha_termino', models.DateField(blank=True, null=True, verbose_name='Fecha de término')),
                ('fecha_retorno', models.DateField(blank=True, null=True, verbose_name='Fecha de retorno')),
                ('es_pendiente', models.BooleanField(default=False, verbose_name='Corresponde a vacaciones pendientes')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Contrato')),
            ],
            options={
                'verbose_name': 'Vacación',
                'verbose_name_plural': 'Vacaciones',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'Contratación'), (2, 'Contratación de reemplazo'), (3, 'Renovación de contrato'), (4, 'Traslado')], default=1)),
                ('categoria', models.PositiveSmallIntegerField(choices=[(1, 'Docente Directivo'), (2, 'Docente'), (3, 'Asistente de Educación'), (4, 'Otro Profesional')], default=2)),
                ('cargo', models.CharField(max_length=250)),
                ('horas', models.PositiveIntegerField(verbose_name='Horas de contrato')),
                ('sueldo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sueldo a percibir')),
                ('asignacion_funcion', models.PositiveIntegerField(blank=True, null=True, verbose_name='Asignación por función')),
                ('asignacion_locomocion', models.PositiveIntegerField(blank=True, null=True, verbose_name='Asignación por locomoción')),
                ('tipo_contrato', models.PositiveSmallIntegerField(choices=[(1, 'Indefinido'), (2, 'A plazo'), (3, 'Reemplazo')], default=1)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('justificacion', models.CharField(max_length=255, verbose_name='Justificación')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.Contrato')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Entidad')),
                ('postulantes', models.ManyToManyField(blank=True, to='rrhh.Persona')),
                ('reemplazando_licencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.Licencia', verbose_name='En reemplazo de (licencia)')),
                ('reemplazando_permiso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.Permiso', verbose_name='En reemplazo de (permiso)')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
            },
        ),
        migrations.CreateModel(
            name='RepresentanteLegal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Entidad', verbose_name='Fundación')),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Contrato', verbose_name='Responsable legal')),
            ],
            options={
                'verbose_name': 'Representante Legal',
                'verbose_name_plural': 'Representates Legales',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_acceso', models.PositiveSmallIntegerField(choices=[(1, 'Invitado'), (2, 'Docente'), (3, 'Docente administrativo'), (4, 'Director'), (5, 'Departamental'), (6, 'Asesor'), (7, 'Administrador')], default=1, verbose_name='Nivel de acceso')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Perfil')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuarios',
            },
        ),
        migrations.CreateModel(
            name='Perfeccionamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Nombre del título')),
                ('es_educacion', models.BooleanField(default=True, verbose_name='Títulado en educación')),
                ('grado_academico', models.CharField(max_length=255, verbose_name='Grado académico')),
                ('fecha_titulacion', models.DateField(verbose_name='Fecha de titulación')),
                ('casa_formadora', models.CharField(max_length=255)),
                ('area_titulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.AreaTitulo', verbose_name='Área del título')),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.Especialidad')),
                ('mencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.Mencion', verbose_name='Mención')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Persona')),
            ],
            options={
                'verbose_name': 'Perfeccionamiento de persona',
                'verbose_name_plural': 'Perfeccionamientos de personas',
            },
        ),
        migrations.AddField(
            model_name='mencion',
            name='tipo_titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.TipoTitulo', verbose_name='Tipo de título'),
        ),
        migrations.AddField(
            model_name='licencia',
            name='tipo_licencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.TipoLicencia', verbose_name='Tipo de licencia'),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salud', models.PositiveSmallIntegerField(choices=[(1, 'Fonasa'), (2, 'Isapre')], default=1, verbose_name='Sistema de salud')),
                ('fecha_ingreso_docente', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso como docente')),
                ('fecha_ingreso_sea', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso al SEA')),
                ('estado', models.PositiveSmallIntegerField(choices=[(1, 'Empleado'), (2, 'Misionero')], default=1, verbose_name='Estado funcionario')),
                ('tipo_misionero', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Licencia misionera'), (2, 'Credencial misionera'), (2, 'Credencial ministerial')], null=True, verbose_name='Tipo de Misionero')),
                ('puntos', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('afp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.AFP', verbose_name='AFP')),
                ('isapre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.Isapre')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Persona')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
            },
        ),
        migrations.CreateModel(
            name='Finiquito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_baja', models.PositiveSmallIntegerField(choices=[(1, 'Término de contrato'), (2, 'Finiquito de mutuo acuerdo'), (3, 'Finiquito por parte del empleador'), (4, 'Renuncia voluntaria')], default=1, verbose_name='Razón de baja')),
                ('descripcion', models.TextField(max_length=1500, verbose_name='Descripción')),
                ('voto_traslado', models.PositiveIntegerField(blank=True, null=True, verbose_name='Voto de autorización de traslado')),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Contrato')),
            ],
            options={
                'verbose_name': 'Finiquito de empleado',
                'verbose_name_plural': 'Finiquitos de empleados',
            },
        ),
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.PositiveSmallIntegerField(choices=[(1, 'Aceptada'), (2, 'Pendiente'), (3, 'Rechazada'), (4, 'En espera de candidatos'), (5, 'Pendiente de aprobación'), (6, 'Aprobada, lista para contratar'), (7, 'Aprobada y contratado')], default=2)),
                ('observaciones', models.TextField(blank=True, max_length=2500, null=True)),
                ('voto', models.CharField(blank=True, max_length=150, null=True, verbose_name='Voto de autorización')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Solicitud')),
            ],
            options={
                'verbose_name': 'Estado de solicitud',
                'verbose_name_plural': 'Estados de solicitudes',
            },
        ),
        migrations.CreateModel(
            name='EstadoContratacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.PositiveSmallIntegerField(choices=[(1, 'Iniciado'), (2, 'Listo para firmar'), (3, 'En revisión'), (4, 'Firmado')], default=2)),
                ('observaciones', models.TextField(blank=True, max_length=2500, null=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Contrato')),
            ],
            options={
                'verbose_name': 'Estado de contratación',
                'verbose_name_plural': 'Estados de contrataciones',
            },
        ),
        migrations.AddField(
            model_name='especialidad',
            name='tipo_titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.TipoTitulo', verbose_name='Tipo de título'),
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrevistador', models.CharField(max_length=255)),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'Felicitaciones'), (2, 'Recomendaciones')], default=1)),
                ('contenido', models.TextField()),
                ('acuerdos', models.TextField()),
                ('fecha', models.DateField()),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Contrato')),
            ],
            options={
                'verbose_name': 'Entevista',
                'verbose_name_plural': 'Entrevistas',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('contrato', 'Contrato'), ('conocimiento reglamento', 'Toma de conocimiento del Reglamento Interno'), ('autorizacion diezmo', 'Autorización de descuento de diezmo'), ('autorizacion imagen', 'Autorización de uso de imagen'), ('permiso', 'Permiso'), ('licencia', 'Licencia'), ('finiquito', 'Finiquito'), ('perfeccionamiento', 'Perfeccionamiento'), ('otro', 'Otro')], default='otro', max_length=150)),
                ('documento', models.FileField(upload_to='rrhh/documentos')),
                ('fecha_carga', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.Contrato')),
                ('finiquito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.Finiquito')),
                ('licencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.Licencia')),
                ('perfeccionamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.Perfeccionamiento')),
                ('permiso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.Permiso')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='DistribucionHoras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.PositiveIntegerField(verbose_name='Horas')),
                ('tipo_horas', models.PositiveSmallIntegerField(choices=[(1, 'Sostenedor'), (2, 'PIE'), (3, 'SEP')], default=1, verbose_name='Tipo de horas')),
                ('jornada_trabajo', models.PositiveSmallIntegerField(choices=[('completa', 'Completa'), ('media', 'Media'), ('noche', 'Noche')], default=1, verbose_name='Jornada de trabajo')),
                ('hora_inicio_jornada', models.TimeField(verbose_name='Inicio de jornada')),
                ('hora_termino_jornada', models.TimeField(verbose_name='Término de jornada')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Contrato')),
            ],
            options={
                'verbose_name': 'Distribución de horas',
                'verbose_name_plural': 'Distribuciones de horas',
            },
        ),
        migrations.CreateModel(
            name='DiasPendientesVacacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_vacacion', models.PositiveIntegerField()),
                ('dias_pendientes', models.PositiveIntegerField(default=0)),
                ('vacacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Vacacion')),
            ],
            options={
                'verbose_name': 'Dias pendientes de vacación',
                'verbose_name_plural': 'Dias pendinetes de vacaciones',
            },
        ),
        migrations.CreateModel(
            name='DetalleFundacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rol de base de datos (RBD)')),
                ('fundacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Entidad', verbose_name='Fundación')),
            ],
            options={
                'verbose_name': 'Detalle de Fundación',
                'verbose_name_plural': 'Detalles de Fundaciones',
            },
        ),
        migrations.CreateModel(
            name='DetalleColegio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rbd', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rol de base de datos (RBD)')),
                ('tipo_subvencion', models.CharField(choices=[('particular', 'Particular'), ('particular_subvencionado', 'Particular Subvencionado'), ('gratuito', 'Gratuito')], default='particular_subvencionado', max_length=75, verbose_name='Tipo de subvención')),
                ('tipo_jornada', models.CharField(choices=[('completa', 'Completa'), ('media', 'Media'), ('noche', 'Noche')], default='completa', max_length=25, verbose_name='Tipo de jornada')),
                ('total_salas', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total de salas')),
                ('capacidad_promedio_salas', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidad promedio de las salas')),
                ('total_matricula_ultimo_anio', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total de matricula el último año')),
                ('total_profesores_aula', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total de profesores de aula')),
                ('total_profesionales_educacion', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total de profesionales de la educación')),
                ('total_asistentes_educacion', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total de asistentes de la educación')),
                ('total_alumnos_pie', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total de alumnos en PIE')),
                ('indice_vulnerabilidad', models.CharField(blank=True, max_length=25, null=True, verbose_name='Índice de vulnerabilidad')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Entidad')),
            ],
            options={
                'verbose_name': 'Detalle del Colegio',
                'verbose_name_plural': 'Detalles de los Colegios',
            },
        ),
        migrations.CreateModel(
            name='DatosBancarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cuenta', models.PositiveSmallIntegerField(choices=[(1, 'Cuenta vista'), (2, 'Cuenta corriente'), (3, 'Chequera electrónica')], default=1)),
                ('numero', models.PositiveIntegerField()),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Banco')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Funcionario')),
            ],
            options={
                'verbose_name': 'Documento de funcionario',
                'verbose_name_plural': 'Documentos de funcionarios',
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Entidad'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='funcion_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcion_principal', to='rrhh.Funcion', verbose_name='Función principal'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='funcion_secundaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcion_secundaria', to='rrhh.Funcion', verbose_name='Función secundaria'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Funcionario'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='reemplazando_licencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reemplazando_licencia', to='rrhh.Licencia', verbose_name='En reemplazo de (licencia)'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='reemplazando_permiso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reemplazando_permiso', to='rrhh.Permiso', verbose_name='En reemplazo de (permiso)'),
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Region', verbose_name='Región')),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Comuna'),
        ),
        migrations.CreateModel(
            name='AcuerdoContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acuerdo', models.TextField(verbose_name='Acuerdo pactado')),
                ('monto', models.PositiveIntegerField(blank=True, null=True, verbose_name='Monto pactado')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Contrato')),
            ],
            options={
                'verbose_name': 'Acuerdo de Contrato',
                'verbose_name_plural': 'Acuerdos de Contratos',
            },
        ),
    ]
