# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-01 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrevistador', models.CharField(max_length=255)),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'Felicitaciones'), (2, 'Recomendaciones')], default=1)),
                ('contenido', models.TextField()),
                ('acuerdos', models.TextField()),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Funcionario')),
            ],
        ),
    ]
