# Generated by Django 2.2 on 2021-09-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecolegio',
            name='tipo_subvencion',
            field=models.CharField(choices=[('particular_subvencionado', 'Particular Subvencionado'), ('particular', 'Particular'), ('gratuito', 'Gratuito')], default='particular_subvencionado', max_length=75, verbose_name='Tipo de subvención'),
        ),
    ]
