# Generated by Django 2.2 on 2021-09-10 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AlterField(
            model_name='detallecolegio',
            name='estado',
            field=models.CharField(choices=[('gratuito', 'Gratuito'), ('particular', 'Particular'), ('particular_subvencionado', 'Particular Subvencionado')], default='particular_subvencionado', max_length=50),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='dependiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.Entidad', verbose_name='Depende de'),
        ),
    ]
