# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-26 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0004_auto_20200623_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencia',
            name='folio_licencia',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Folio de la licencia'),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='total_dias',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total de días de licencia'),
        ),
    ]
