# Generated by Django 2.2 on 2021-10-06 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0005_auto_20210930_1552'),
        ('rrhh', '0003_auto_20210927_1549'),
    ]

    operations = [
    ]
