# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-26 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0005_auto_20200626_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencia',
            name='dias_habiles',
            field=models.BooleanField(default=True, verbose_name='Corresponde a días hábiles'),
        ),
    ]
