# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-30 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0007_auto_20200626_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacacion',
            name='dias_pendiente',
            field=models.IntegerField(default=0, verbose_name='Días pendientes'),
        ),
    ]
