# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-03 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga_horaria', '0017_profesor_fundacion'),
        ('rrhh', '0008_vacacion_dias_pendiente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.PositiveSmallIntegerField(choices=[(1, 'Docente Directivo'), (2, 'Docente'), (3, 'Asistente de Educación'), (4, 'Personal de la Fundación'), (5, 'Otro Profesional')], default=5)),
                ('funcion_principal', models.CharField(max_length=150, verbose_name='Función principal')),
                ('funcion_secundaria', models.CharField(max_length=150, verbose_name='Función secundaria')),
                ('tipo_contrato', models.PositiveSmallIntegerField(choices=[(1, 'Indefinido'), (2, 'A plazo'), (3, 'Reemplazo')], default=1, verbose_name='Tipo de contrato')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_termino', models.DateField(blank=True, null=True, verbose_name='Fecha de Término')),
                ('horas', models.TimeField()),
                ('tipo_horas', models.PositiveSmallIntegerField(choices=[(1, 'Sostenedor'), (2, 'PIE'), (3, 'SEP')], default=1, verbose_name='Tipo de horas')),
                ('salud', models.PositiveSmallIntegerField(choices=[(1, 'Fonasa'), (2, 'Isapre')], default=1, verbose_name='Sistema de salud')),
                ('isapre', models.CharField(blank=True, max_length=150, null=True)),
                ('afp', models.CharField(max_length=150)),
                ('jornada_trabajo', models.PositiveSmallIntegerField(choices=[(1, 'Completa'), (2, 'Media'), (3, 'Noche')], default=1, verbose_name='Jornada de trabajo')),
                ('hora_inicio_jornada', models.TimeField(verbose_name='Inicio de jornada')),
                ('hora_termino_jornada', models.TimeField(verbose_name='Término de jornada')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga_horaria.Colegio')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Funcionario')),
                ('reemplazando', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carga_horaria.Profesor')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.AlterField(
            model_name='licencia',
            name='total_dias',
            field=models.IntegerField(default=0, verbose_name='Total de días de licencia'),
            preserve_default=False,
        ),
    ]
