# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-03 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0009_auto_20200803_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='horas',
        ),
    ]
