# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-06 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0011_contrato_horas'),
    ]

    operations = [
        migrations.CreateModel(
            name='AFP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'AFP',
                'verbose_name_plural': 'AFPs',
            },
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'Funcion principal'), (2, 'Función secundaria')], default=1, verbose_name='Tipo de función')),
            ],
            options={
                'verbose_name': 'Función',
                'verbose_name_plural': 'Funciones',
            },
        ),
        migrations.CreateModel(
            name='Isapre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Isapre',
                'verbose_name_plural': 'Isapres',
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='vigente',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='afp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.AFP'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='funcion_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcion_principal', to='rrhh.Funcion', verbose_name='Función principal'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='funcion_secundaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcion_secundaria', to='rrhh.Funcion', verbose_name='Función secundaria'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='isapre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.Isapre'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='reemplazando',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.Contrato', verbose_name='En reemplazo de'),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='tipo_licencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.TipoLicencia', verbose_name='Tipo de licencia'),
        ),
    ]
