# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-10 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0012_auto_20200806_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='antiguedad_docente_meses',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='antiguedad_sea_meses',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Empleado'), (2, 'Misionero')], default=1, verbose_name='Estado funcionario'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='fecha_titulacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de titulación'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='puntos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='tipo_misionero',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Licencia misionera'), (2, 'Credencial misionera'), (2, 'Credencial ministerial')], default=1, null=True, verbose_name='Tipo de Misionero'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='afp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.AFP', verbose_name='AFP'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='categoria',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Docente Directivo'), (2, 'Docente'), (3, 'Asistente de Educación'), (4, 'Personal de la Fundación'), (5, 'Otro Profesional')], verbose_name='Categoría'),
        ),
    ]
