# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-19 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import rrhh.models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0013_auto_20200810_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='puntos',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='rut',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='tipo_misionero',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Licencia misionera'), (2, 'Credencial misionera'), (2, 'Credencial ministerial')], null=True, verbose_name='Tipo de Misionero'),
        ),
    ]
