# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-25 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0014_auto_20200819_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finiquito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_baja', models.PositiveSmallIntegerField(choices=[(1, 'Término de contrato'), (2, 'Finiquito de mutuo acuerdo'), (3, 'Finiquito por parte del empleador'), (4, 'Renuncia voluntaria')], default=1, verbose_name='Razón de baja')),
                ('descripcion', models.TextField(max_length=1500, verbose_name='Descripción')),
                ('archivo', models.FileField(upload_to='', verbose_name='Finiquito')),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Contrato')),
            ],
        ),
    ]
