# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-25 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0015_finiquito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finiquito',
            options={'verbose_name': 'Finiquito', 'verbose_name_plural': 'Finiquitos'},
        ),
        migrations.AlterField(
            model_name='finiquito',
            name='archivo',
            field=models.FileField(upload_to='rrhh/finiquitos', verbose_name='Finiquito'),
        ),
    ]
