# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-09-02 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0016_auto_20200825_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licencia',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='vacacion',
            name='funcionario',
        ),
        migrations.AddField(
            model_name='licencia',
            name='contrato',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='rrhh.Contrato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacacion',
            name='contrato',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='rrhh.Contrato'),
            preserve_default=False,
        ),
    ]
