# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-10-30 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0018_auto_20200908_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('abrev', models.CharField(max_length=50, verbose_name='Abreviación')),
                ('rbd', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rol de base de datos (RBD)')),
                ('estado', models.CharField(choices=[('gratuito', 'Gratuito'), ('particular_subvencionado', 'Particular Subvencionado'), ('particular', 'Particular')], default='particular_subvencionado', max_length=25)),
                ('tipo_jornada', models.CharField(choices=[('media', 'Media Jornada'), ('completa', 'Jornada Completa')], default='completa', max_length=25)),
                ('total_salas', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total de salas')),
                ('capacidad_promedio_salas', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidad promedio de las salas')),
                ('total_matricula_ultimo_anio', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total de matricula el último año')),
                ('total_profesores_aula', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total de profesores de aula')),
                ('total_profesionales_educacion', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total de profesionales de la educación')),
                ('total_asistentes_educacion', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total de asistentes de la educación')),
                ('total_alumnos_pie', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total de alumnos en PIE')),
                ('indice_vulnerabilidad', models.CharField(blank=True, max_length=25, null=True, verbose_name='Índice de vulnerabilidad')),
            ],
            options={
                'verbose_name': 'Colegio',
                'verbose_name_plural': 'Colegios',
            },
        ),
        migrations.CreateModel(
            name='DocumentoFuncionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('documento', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso_docente', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso como docente')),
                ('fecha_ingreso_sea', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso al SEA')),
                ('estado', models.PositiveSmallIntegerField(choices=[(1, 'Empleado'), (2, 'Misionero')], default=1, verbose_name='Estado funcionario')),
                ('tipo_misionero', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Licencia misionera'), (2, 'Credencial misionera'), (2, 'Credencial ministerial')], null=True, verbose_name='Tipo de Misionero')),
                ('puntos', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
            },
        ),
        migrations.CreateModel(
            name='Fundacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Fundación',
                'verbose_name_plural': 'Fundaciones',
            },
        ),
        migrations.CreateModel(
            name='Perfeccionamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casa_formadora', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('grado_academico', models.CharField(max_length=255, verbose_name='Grado académico')),
                ('fecha_titulacion', models.DateField()),
                ('documento_respaldo', models.FileField(upload_to='', verbose_name='Documento de respaldo')),
            ],
            options={
                'verbose_name': 'Perfeccionamiento',
                'verbose_name_plural': 'Perfeccionamientos',
            },
        ),
        migrations.CreateModel(
            name='TIpoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('indicaciones', models.TextField(max_length=2500)),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documento',
            },
        ),
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Unión',
                'verbose_name_plural': 'Uniones',
            },
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='contrato',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='casa_formadora',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='fecha_ingreso_docente',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='fecha_ingreso_sea',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='fecha_titulacion',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='puntos',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='tipo_misionero',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='titulo',
        ),
        migrations.AddField(
            model_name='persona',
            name='ciudad',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='persona',
            name='comuna',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='persona',
            name='profesion',
            field=models.CharField(default='', max_length=255, verbose_name='Profesión'),
        ),
        migrations.AddField(
            model_name='persona',
            name='titulado',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Archivo',
        ),
        migrations.AddField(
            model_name='perfeccionamiento',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Persona'),
        ),
        migrations.AddField(
            model_name='fundacion',
            name='union',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Union'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Persona'),
        ),
        migrations.AddField(
            model_name='documentofuncionario',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Funcionario'),
        ),
        migrations.AddField(
            model_name='documentofuncionario',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.TIpoDocumento'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='fundacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Fundacion'),
        ),
    ]
