# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-11-02 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0019_auto_20201030_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='persona',
        ),
        migrations.AddField(
            model_name='contrato',
            name='funcionario',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='rrhh.Funcionario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contrato',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Colegio'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Persona'),
        ),
    ]
