# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-11-03 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0020_auto_20201102_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundacion',
            name='descripcion',
            field=models.TextField(blank=True, max_length=2500, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='union',
            name='descripcion',
            field=models.TextField(blank=True, max_length=2500, null=True, verbose_name='Descripción'),
        ),
    ]
