# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-11-09 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0021_auto_20201103_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField(max_length=2500, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
            },
        ),
        migrations.CreateModel(
            name='ContratoColegio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.PositiveSmallIntegerField(choices=[(1, 'Docente Directivo'), (2, 'Docente'), (3, 'Asistente de Educación'), (4, 'Otro Profesional')], verbose_name='Categoría')),
                ('tipo_contrato', models.PositiveSmallIntegerField(choices=[(1, 'Indefinido'), (2, 'A plazo'), (3, 'Reemplazo')], default=1, verbose_name='Tipo de contrato')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_termino', models.DateField(blank=True, null=True, verbose_name='Fecha de Término')),
                ('horas_total', models.PositiveIntegerField(verbose_name='Horas contratadas')),
                ('vigente', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contrato de colegio',
                'verbose_name_plural': 'Contratos de colegios',
            },
        ),
        migrations.CreateModel(
            name='ContratoFundacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.PositiveSmallIntegerField(choices=[(1, 'Personal de fundación'), (2, 'Otro Profesional')], verbose_name='Categoría')),
                ('tipo_contrato', models.PositiveSmallIntegerField(choices=[(1, 'Indefinido'), (2, 'A plazo'), (3, 'Reemplazo')], default=1, verbose_name='Tipo de contrato')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_termino', models.DateField(blank=True, null=True, verbose_name='Fecha de Término')),
                ('horas_total', models.PositiveIntegerField(verbose_name='Horas contratadas')),
                ('vigente', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contrato de fundación',
                'verbose_name_plural': 'Contratos de fundaciones',
            },
        ),
        migrations.CreateModel(
            name='ContratoUnion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.PositiveSmallIntegerField(choices=[(1, 'Personal de unión'), (2, 'Otro Profesional')], verbose_name='Categoría')),
                ('tipo_contrato', models.PositiveSmallIntegerField(choices=[(1, 'Indefinido'), (2, 'A plazo'), (3, 'Reemplazo')], default=1, verbose_name='Tipo de contrato')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_termino', models.DateField(blank=True, null=True, verbose_name='Fecha de Término')),
                ('horas_total', models.PositiveIntegerField(verbose_name='Horas contratadas')),
                ('vigente', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contrato de unión',
                'verbose_name_plural': 'Contratos de uniones',
            },
        ),
        migrations.CreateModel(
            name='DatosBancarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cuenta', models.PositiveSmallIntegerField(choices=[(1, 'Cuenta vista'), (2, 'Cuenta corriente'), (3, 'Chequera electrónica')], default=1)),
                ('numero', models.PositiveIntegerField()),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Banco')),
            ],
            options={
                'verbose_name': 'Documento de funcionario',
                'verbose_name_plural': 'Documentos de funcionarios',
            },
        ),
        migrations.CreateModel(
            name='DistribucionHoras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.PositiveIntegerField(verbose_name='Horas')),
                ('tipo_horas', models.PositiveSmallIntegerField(choices=[(1, 'Sostenedor'), (2, 'PIE'), (3, 'SEP')], default=1, verbose_name='Tipo de horas')),
                ('jornada_trabajo', models.PositiveSmallIntegerField(choices=[(1, 'Completa'), (2, 'Media'), (3, 'Noche')], default=1, verbose_name='Jornada de trabajo')),
                ('hora_inicio_jornada', models.TimeField(verbose_name='Inicio de jornada')),
                ('hora_termino_jornada', models.TimeField(verbose_name='Término de jornada')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.ContratoColegio')),
            ],
            options={
                'verbose_name': 'Distribución de horas',
                'verbose_name_plural': 'Distribuciones de horas',
            },
        ),
        migrations.CreateModel(
            name='FiniquitoFundacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_baja', models.PositiveSmallIntegerField(choices=[(1, 'Término de contrato'), (2, 'Finiquito de mutuo acuerdo'), (3, 'Finiquito por parte del empleador'), (4, 'Renuncia voluntaria')], default=1, verbose_name='Razón de baja')),
                ('descripcion', models.TextField(max_length=1500, verbose_name='Descripción')),
                ('archivo', models.FileField(upload_to='rrhh/finiquitos', verbose_name='Finiquito')),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rrhh.ContratoFundacion')),
            ],
            options={
                'verbose_name': 'Finiquito de empleado de fundación',
                'verbose_name_plural': 'Finiquitos de empleados de fundaciones',
            },
        ),
        migrations.CreateModel(
            name='FiniquitoUnion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_baja', models.PositiveSmallIntegerField(choices=[(1, 'Término de contrato'), (2, 'Finiquito de mutuo acuerdo'), (3, 'Finiquito por parte del empleador'), (4, 'Renuncia voluntaria')], default=1, verbose_name='Razón de baja')),
                ('descripcion', models.TextField(max_length=1500, verbose_name='Descripción')),
                ('archivo', models.FileField(upload_to='rrhh/finiquitos', verbose_name='Finiquito')),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rrhh.ContratoUnion')),
            ],
            options={
                'verbose_name': 'Finiquito de empleado de unión',
                'verbose_name_plural': 'Finiquitos de empleados de uniones',
            },
        ),
        migrations.CreateModel(
            name='LicenciaFuncionarioFundacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_licencia_descripcion', models.TextField(blank=True, max_length=500, null=True, verbose_name='Tipo de licencia')),
                ('folio_licencia', models.CharField(blank=True, max_length=30, null=True, verbose_name='Folio de la licencia')),
                ('total_dias', models.IntegerField(verbose_name='Total de días de licencia')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('total_feriados', models.IntegerField(default=0, verbose_name='Total de feriados en el periodo de la licencia')),
                ('fecha_termino', models.DateField(blank=True, null=True, verbose_name='Fecha de término')),
                ('fecha_retorno', models.DateField(blank=True, null=True, verbose_name='Fecha de retorno')),
                ('dias_habiles', models.BooleanField(default=True, verbose_name='Corresponde a días hábiles')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.ContratoFundacion')),
                ('tipo_licencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.TipoLicencia', verbose_name='Tipo de licencia')),
            ],
            options={
                'verbose_name': 'Licencia de empleado de fundación',
                'verbose_name_plural': 'Licencias de empleados de fundaciones',
            },
        ),
        migrations.CreateModel(
            name='LicenciaFuncionarioUnion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_licencia_descripcion', models.TextField(blank=True, max_length=500, null=True, verbose_name='Tipo de licencia')),
                ('folio_licencia', models.CharField(blank=True, max_length=30, null=True, verbose_name='Folio de la licencia')),
                ('total_dias', models.IntegerField(verbose_name='Total de días de licencia')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('total_feriados', models.IntegerField(default=0, verbose_name='Total de feriados en el periodo de la licencia')),
                ('fecha_termino', models.DateField(blank=True, null=True, verbose_name='Fecha de término')),
                ('fecha_retorno', models.DateField(blank=True, null=True, verbose_name='Fecha de retorno')),
                ('dias_habiles', models.BooleanField(default=True, verbose_name='Corresponde a días hábiles')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.ContratoUnion')),
                ('tipo_licencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.TipoLicencia', verbose_name='Tipo de licencia')),
            ],
            options={
                'verbose_name': 'Licencia de empleado de unión',
                'verbose_name_plural': 'Licencias de empleados de uniones',
            },
        ),
        migrations.CreateModel(
            name='VacacionFuncionarioFundacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_dias', models.IntegerField(verbose_name='Total de días de vacaciones')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('total_feriados', models.IntegerField(default=0, verbose_name='Total de feriados en el periodo de vacaciones')),
                ('fecha_termino', models.DateField(blank=True, null=True, verbose_name='Fecha de término')),
                ('fecha_retorno', models.DateField(blank=True, null=True, verbose_name='Fecha de retorno')),
                ('dias_pendiente', models.IntegerField(default=0, verbose_name='Días pendientes')),
                ('es_pendiente', models.BooleanField(default=False, verbose_name='Corresponde a vacaciones pendientes')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.ContratoFundacion')),
            ],
            options={
                'verbose_name': 'Vacación de empleado de fundación',
                'verbose_name_plural': 'Vacaciones de empleados de fundaciones',
            },
        ),
        migrations.CreateModel(
            name='VacacionFuncionarioUnion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_dias', models.IntegerField(verbose_name='Total de días de vacaciones')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('total_feriados', models.IntegerField(default=0, verbose_name='Total de feriados en el periodo de vacaciones')),
                ('fecha_termino', models.DateField(blank=True, null=True, verbose_name='Fecha de término')),
                ('fecha_retorno', models.DateField(blank=True, null=True, verbose_name='Fecha de retorno')),
                ('dias_pendiente', models.IntegerField(default=0, verbose_name='Días pendientes')),
                ('es_pendiente', models.BooleanField(default=False, verbose_name='Corresponde a vacaciones pendientes')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.ContratoUnion')),
            ],
            options={
                'verbose_name': 'Vacación de empleado de unión',
                'verbose_name_plural': 'Vacaciones de empleados de uniones',
            },
        ),
        migrations.RenameModel(
            old_name='Finiquito',
            new_name='FiniquitoColegio',
        ),
        migrations.RenameModel(
            old_name='Licencia',
            new_name='LicenciaFuncionarioColegio',
        ),
        migrations.RenameModel(
            old_name='Vacacion',
            new_name='VacacionFuncionarioColegio',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='afp',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='colegio',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='funcion_principal',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='funcion_secundaria',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='isapre',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='reemplazando',
        ),
        migrations.AlterModelOptions(
            name='documentofuncionario',
            options={'verbose_name': 'Documento de funcionario', 'verbose_name_plural': 'Documentos de funcionarios'},
        ),
        migrations.AlterModelOptions(
            name='entrevista',
            options={'verbose_name': 'Entevista de empleado de colegio', 'verbose_name_plural': 'Entrevistas de empleados de colegios'},
        ),
        migrations.AlterModelOptions(
            name='finiquitocolegio',
            options={'verbose_name': 'Finiquito de empleado de colegio', 'verbose_name_plural': 'Finiquitos de empleados de colegios'},
        ),
        migrations.AlterModelOptions(
            name='funcion',
            options={'verbose_name': 'Función de empleado', 'verbose_name_plural': 'Funciones de empleados'},
        ),
        migrations.AlterModelOptions(
            name='licenciafuncionariocolegio',
            options={'verbose_name': 'Licencia de empleado de colegio', 'verbose_name_plural': 'Licencias de empleados de colegios'},
        ),
        migrations.AlterModelOptions(
            name='perfeccionamiento',
            options={'verbose_name': 'Perfeccionamiento de persona', 'verbose_name_plural': 'Perfeccionamientos de personas'},
        ),
        migrations.AlterModelOptions(
            name='vacacionfuncionariocolegio',
            options={'verbose_name': 'Vacación de empleado de colegio', 'verbose_name_plural': 'Vacaciones de empleados de colegios'},
        ),
        migrations.AddField(
            model_name='entrevista',
            name='fecha',
            field=models.DateField(default='2020-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='afp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.AFP', verbose_name='AFP'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='isapre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.Isapre'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='salud',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Fonasa'), (2, 'Isapre')], default=1, verbose_name='Sistema de salud'),
        ),
        migrations.AddField(
            model_name='fundacion',
            name='abrev',
            field=models.CharField(default='', max_length=50, verbose_name='Abreviación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='union',
            name='abrev',
            field=models.CharField(default='', max_length=50, verbose_name='Abreviación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='afp',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='estado',
            field=models.CharField(max_length=25, choices=[('particular_subvencionado', 'Particular Subvencionado'), ('particular', 'Particular'), ('gratuito', 'Gratuito')], default='particular_subvencionado'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='fundacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Fundacion', verbose_name='Fundación'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='tipo_jornada',
            field=models.CharField(max_length=25, choices=[('completa', 'Completa'), ('media', 'Media'), ('noche', 'Noche')], default='completa', verbose_name='Tipo de jornada'),
        ),
        migrations.AlterField(
            model_name='documentofuncionario',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.TipoDocumento'),
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.ContratoColegio'),
        ),
        migrations.AlterField(
            model_name='finiquitocolegio',
            name='contrato',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rrhh.ContratoColegio'),
        ),
        migrations.AlterField(
            model_name='funcion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='isapre',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='licenciafuncionariocolegio',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.ContratoColegio'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='profesion',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Profesión'),
        ),
        migrations.AlterField(
            model_name='vacacionfuncionariocolegio',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.ContratoColegio'),
        ),
        migrations.DeleteModel(
            name='Contrato',
        ),
        migrations.AddField(
            model_name='datosbancarios',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Funcionario'),
        ),
        migrations.AddField(
            model_name='contratounion',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Funcionario'),
        ),
        migrations.AddField(
            model_name='contratounion',
            name='reemplazando',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.ContratoUnion', verbose_name='En reemplazo de'),
        ),
        migrations.AddField(
            model_name='contratounion',
            name='union',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Union', verbose_name='Unión'),
        ),
        migrations.AddField(
            model_name='contratofundacion',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Funcionario'),
        ),
        migrations.AddField(
            model_name='contratofundacion',
            name='fundacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Fundacion', verbose_name='Fundación'),
        ),
        migrations.AddField(
            model_name='contratofundacion',
            name='reemplazando',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.ContratoFundacion', verbose_name='En reemplazo de'),
        ),
        migrations.AddField(
            model_name='contratocolegio',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Colegio'),
        ),
        migrations.AddField(
            model_name='contratocolegio',
            name='funcion_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcion_principal', to='rrhh.Funcion', verbose_name='Función principal'),
        ),
        migrations.AddField(
            model_name='contratocolegio',
            name='funcion_secundaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcion_secundaria', to='rrhh.Funcion', verbose_name='Función secundaria'),
        ),
        migrations.AddField(
            model_name='contratocolegio',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Funcionario'),
        ),
        migrations.AddField(
            model_name='contratocolegio',
            name='reemplazando',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.ContratoColegio', verbose_name='En reemplazo de'),
        ),
    ]
