# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-11-09 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0022_auto_20201109_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.PositiveSmallIntegerField(choices=[(1, 'Aceptada'), (2, 'Pendiente'), (3, 'Rechazada')], default=2)),
                ('observaciones', models.TextField(max_length=2500)),
                ('voto', models.CharField(max_length=150, verbose_name='Voto de autorización')),
                ('fecha', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado de solicitud',
                'verbose_name_plural': 'Estados de solicitudes',
            },
        ),
        migrations.CreateModel(
            name='SolicitudContratacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=250)),
                ('horas', models.IntegerField(verbose_name='Horas de contrato')),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('justificacion', models.CharField(max_length=255, verbose_name='Justificación')),
            ],
            options={
                'verbose_name': 'Solicitud de contratación',
                'verbose_name_plural': 'Solicitudes de contratación',
            },
        ),
        migrations.AlterField(
            model_name='colegio',
            name='estado',
            field=models.CharField(choices=[('gratuito', 'Gratuito'), ('particular_subvencionado', 'Particular Subvencionado'), ('particular', 'Particular')], default='particular_subvencionado', max_length=25),
        ),
        migrations.AlterField(
            model_name='distribucionhoras',
            name='jornada_trabajo',
            field=models.PositiveSmallIntegerField(choices=[('completa', 'Completa'), ('media', 'Media'), ('noche', 'Noche')], default=1, verbose_name='Jornada de trabajo'),
        ),
        migrations.AlterField(
            model_name='documentofuncionario',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.TipoDocumento'),
        ),
        migrations.AddField(
            model_name='solicitudcontratacion',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Colegio'),
        ),
        migrations.AddField(
            model_name='solicitudcontratacion',
            name='postulantes',
            field=models.ManyToManyField(to='rrhh.Persona'),
        ),
        migrations.AddField(
            model_name='estadosolicitud',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.SolicitudContratacion'),
        ),
    ]
