# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-11-24 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0025_auto_20201116_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudRenovacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contrato', models.PositiveSmallIntegerField(choices=[(1, 'Indefinido'), (2, 'A plazo'), (3, 'Reemplazo')], default=1)),
                ('horas', models.PositiveIntegerField(verbose_name='Horas de contrato')),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('estado', models.PositiveSmallIntegerField(choices=[(1, 'Aceptada'), (2, 'Rechazada'), (3, 'Pendiente')], default=3)),
                ('voto', models.CharField(blank=True, max_length=150, null=True, verbose_name='Voto de autorización')),
                ('observaciones', models.TextField(blank=True, max_length='2100', null=True)),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rrhh.ContratoColegio')),
            ],
            options={
                'verbose_name': 'Solicitud de renovación',
                'verbose_name_plural': 'Solicitudes de renovación',
            },
        ),
        migrations.AlterField(
            model_name='documentofuncionario',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.TipoDocumento'),
        ),
    ]
