# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-11-24 20:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rrhh', '0026_auto_20201124_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudrenovacion',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentofuncionario',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.TipoDocumento'),
        ),
        migrations.AlterField(
            model_name='solicitudrenovacion',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pendiente'), (2, 'Aceptada'), (3, 'Rechazada')], default=1),
        ),
    ]
