# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-11-29 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0028_auto_20201126_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='finiquitocolegio',
            name='voto_traslado',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Voto de autorización de traslado'),
        ),
        migrations.AlterField(
            model_name='documentofuncionario',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.TipoDocumento'),
        ),
        migrations.AlterField(
            model_name='solicitudcontratacion',
            name='horas',
            field=models.PositiveIntegerField(verbose_name='Horas de contrato'),
        ),
    ]
