# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-11-30 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0030_auto_20201129_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'Contratación'), (2, 'Contratación de reemplazo'), (3, 'Renovación de contrato'), (4, 'Traslado')], default=1)),
                ('categoria', models.PositiveSmallIntegerField(choices=[(1, 'Docente Directivo'), (2, 'Docente'), (3, 'Asistente de Educación'), (4, 'Otro Profesional')], default=2)),
                ('cargo', models.CharField(max_length=250)),
                ('horas', models.PositiveIntegerField(verbose_name='Horas de contrato')),
                ('tipo_contrato', models.PositiveSmallIntegerField(choices=[(1, 'Indefinido'), (2, 'A plazo'), (3, 'Reemplazo')], default=1)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('justificacion', models.CharField(max_length=255, verbose_name='Justificación')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Colegio')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.ContratoColegio')),
                ('postulantes', models.ManyToManyField(blank=True, to='rrhh.Persona')),
                ('reemplazando_licencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.LicenciaFuncionarioColegio', verbose_name='En reemplazo de')),
            ],
            options={
                'verbose_name': 'Solicitud de contratación',
                'verbose_name_plural': 'Solicitudes de contratación',
            },
        ),
        migrations.RemoveField(
            model_name='solicitudcontratacion',
            name='colegio',
        ),
        migrations.RemoveField(
            model_name='solicitudcontratacion',
            name='postulantes',
        ),
        migrations.RemoveField(
            model_name='solicitudcontratacion',
            name='reemplazando_licencia',
        ),
        migrations.RemoveField(
            model_name='solicitudrenovacion',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='solicitudrenovacion',
            name='contrato',
        ),
        migrations.RemoveField(
            model_name='estadosolicitud',
            name='solicitud',
        ),
        migrations.AlterField(
            model_name='documentofuncionario',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.TipoDocumento'),
        ),
        migrations.DeleteModel(
            name='SolicitudContratacion',
        ),
        migrations.DeleteModel(
            name='SolicitudRenovacion',
        ),
    ]
