# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-11-30 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0031_auto_20201130_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadosolicitud',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Solicitud'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentofuncionario',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.TipoDocumento'),
        ),
    ]
