# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-14 21:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rrhh', '0032_auto_20201130_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoContratacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.PositiveSmallIntegerField(choices=[(1, 'Iniciado'), (2, 'Listo para firmar'), (3, 'En revisión'), (4, 'Firmado')], default=2)),
                ('observaciones', models.TextField(blank=True, max_length=2500, null=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estado de contratación',
                'verbose_name_plural': 'Estados de contrataciones',
            },
        ),
        migrations.AlterModelOptions(
            name='solicitud',
            options={'verbose_name': 'Solicitud', 'verbose_name_plural': 'Solicitudes'},
        ),
        migrations.AddField(
            model_name='contratocolegio',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='rrhh/contratos', verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='contratocolegio',
            name='vigente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documentofuncionario',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.TipoDocumento'),
        ),
        migrations.AlterField(
            model_name='estadosolicitud',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Aceptada'), (2, 'Pendiente'), (3, 'Rechazada'), (4, 'En espera de candidatos'), (5, 'Pendiente de aprobación'), (6, 'Aprobada, lista para contratar'), (7, 'Aprobada y contratado')], default=2),
        ),
        migrations.AddField(
            model_name='estadocontratacion',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.ContratoColegio'),
        ),
    ]
