# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-17 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0033_auto_20201214_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoFuncionarioColegio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_dias', models.IntegerField(verbose_name='Total de días de licencia')),
                ('observaciones', models.TextField(max_length=2500, verbose_name='Motivos u observaciones')),
                ('fecha_solicitud', models.DateField(verbose_name='Fecha de solicitud')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('total_feriados', models.IntegerField(default=0, verbose_name='Total de feriados en el periodo de la licencia')),
                ('fecha_termino', models.DateField(blank=True, null=True, verbose_name='Fecha de término')),
                ('fecha_retorno', models.DateField(blank=True, null=True, verbose_name='Fecha de retorno')),
                ('goce_sueldo', models.BooleanField(default=False, verbose_name='Con goce de sueldo')),
                ('dias_habiles', models.BooleanField(default=True, verbose_name='Corresponde a días hábiles')),
                ('voto', models.PositiveIntegerField(blank=True, null=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='rrhh/permisos', verbose_name='Permiso')),
            ],
            options={
                'verbose_name': 'Permiso de empleado de colegio',
                'verbose_name_plural': 'Permisos de empleados de colegios',
            },
        ),
        migrations.AlterField(
            model_name='contratocolegio',
            name='reemplazando_licencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.LicenciaFuncionarioColegio', verbose_name='En reemplazo de (licencia)'),
        ),
        migrations.AlterField(
            model_name='documentofuncionario',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.TipoDocumento'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='reemplazando_licencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.LicenciaFuncionarioColegio', verbose_name='En reemplazo de (licencia)'),
        ),
        migrations.AddField(
            model_name='permisofuncionariocolegio',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.ContratoColegio'),
        ),
        migrations.AddField(
            model_name='contratocolegio',
            name='reemplazando_permiso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.PermisoFuncionarioColegio', verbose_name='En reemplazo de (permiso)'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='reemplazando_permiso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.PermisoFuncionarioColegio', verbose_name='En reemplazo de (permiso)'),
        ),
    ]
