# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-01-22 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0034_auto_20201217_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.PositiveSmallIntegerField(choices=[(1, 'Toma de conocimiento del Reglamento Interno'), (2, 'Autorización de descuento de diezmo'), (3, 'Autorización de uso de imagen')])),
                ('fecha_carga', models.DateTimeField(auto_now=True)),
                ('documento', models.FileField(upload_to='rrhh/DocumentoDePersonal', verbose_name='Documento')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.ContratoColegio')),
            ],
            options={
                'verbose_name': 'Docmuento del personal',
                'verbose_name_plural': 'Documentos del personal',
            },
        ),
        migrations.AlterField(
            model_name='documentofuncionario',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.TipoDocumento'),
        ),
        migrations.AlterField(
            model_name='permisofuncionariocolegio',
            name='total_dias',
            field=models.IntegerField(verbose_name='Total de días de permiso'),
        ),
        migrations.AlterField(
            model_name='permisofuncionariocolegio',
            name='total_feriados',
            field=models.IntegerField(default=0, verbose_name='Total de feriados en el periodo del permiso'),
        ),
    ]
