# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-07-13 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0044_auto_20210712_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiasPendientesVacacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_vacacion', models.PositiveIntegerField(max_length=4)),
                ('dias_pendientes', models.PositiveIntegerField(default=0, max_length=2)),
            ],
            options={
                'verbose_name': 'Dias pendientes de vacación',
                'verbose_name_plural': 'Dias pendinetes de vacaciones',
            },
        ),
        migrations.RemoveField(
            model_name='vacacionfuncionariocolegio',
            name='dias_pendiente',
        ),
        migrations.AddField(
            model_name='vacacionfuncionariocolegio',
            name='anio_vacacion',
            field=models.PositiveIntegerField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='estado',
            field=models.CharField(choices=[('particular', 'Particular'), ('particular_subvencionado', 'Particular Subvencionado'), ('gratuito', 'Gratuito')], default='particular_subvencionado', max_length=25),
        ),
        migrations.AlterField(
            model_name='documentofuncionario',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.TipoDocumento'),
        ),
        migrations.AddField(
            model_name='diaspendientesvacacion',
            name='vacacion_funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.VacacionFuncionarioColegio'),
        ),
    ]
