# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-07-15 16:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rrhh', '0045_auto_20210713_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_perfil', models.PositiveSmallIntegerField(choices=[(1, ''), (2, ''), (3, '')], default=1, verbose_name='Tipo de perfil')),
                ('descripcion', models.TextField(blank=True, max_length=550, null=True, verbose_name='Descripción')),
                ('solo_lectura', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_acceso', models.PositiveSmallIntegerField(choices=[(1, 'Invitado'), (2, 'Docente'), (3, 'Docente administrativo'), (4, 'Director'), (5, 'Departamental'), (6, 'Asesor'), (7, 'Administrador')], default=1, verbose_name='Nivel de acceso')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Perfil')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuarios',
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='estado',
            field=models.CharField(choices=[('particular_subvencionado', 'Particular Subvencionado'), ('gratuito', 'Gratuito'), ('particular', 'Particular')], default='particular_subvencionado', max_length=25),
        ),
        migrations.AlterField(
            model_name='diaspendientesvacacion',
            name='anio_vacacion',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='diaspendientesvacacion',
            name='dias_pendientes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='documentofuncionario',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.TipoDocumento'),
        ),
        migrations.AlterField(
            model_name='vacacionfuncionariocolegio',
            name='anio_vacacion',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
