# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-07-26 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0047_auto_20210726_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegio',
            name='estado',
            field=models.CharField(choices=[('particular', 'Particular'), ('gratuito', 'Gratuito'), ('particular_subvencionado', 'Particular Subvencionado')], default='particular_subvencionado', max_length=25),
        ),
        migrations.AlterField(
            model_name='documentofuncionario',
            name='documento',
            field=models.FileField(upload_to='rrhh/documentosFuncionarios', verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='documentofuncionario',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.TipoDocumento'),
        ),
        migrations.AlterField(
            model_name='documentopersonal',
            name='documento',
            field=models.FileField(upload_to='rrhh/documentosPersonal', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='perfeccionamiento',
            name='documento_respaldo',
            field=models.FileField(upload_to='rrhh/perfeccionamientos', verbose_name='Documento de respaldo'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='rrhh/fotos', verbose_name='Foto de perfil'),
        ),
    ]
