# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-07-27 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0049_auto_20210727_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegio',
            name='estado',
            field=models.CharField(choices=[('particular', 'Particular'), ('particular_subvencionado', 'Particular Subvencionado'), ('gratuito', 'Gratuito')], default='particular_subvencionado', max_length=25),
        ),
        migrations.AlterField(
            model_name='documentofuncionario',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.TipoDocumento'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.Ciudad'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.Comuna'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='religion',
            field=models.BooleanField(default=True, verbose_name='Adventista del Séptimo día'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.PositiveIntegerField(help_text='Número de 9 dígitos', verbose_name='Teléfono'),
        ),
    ]
