# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-07-27 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0050_auto_20210727_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='comuna',
        ),
        migrations.AlterField(
            model_name='colegio',
            name='estado',
            field=models.CharField(choices=[('particular_subvencionado', 'Particular Subvencionado'), ('gratuito', 'Gratuito'), ('particular', 'Particular')], default='particular_subvencionado', max_length=25),
        ),
        migrations.AlterField(
            model_name='documentofuncionario',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.TipoDocumento'),
        ),
    ]
