# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-08-03 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0051_auto_20210727_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaTitulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(max_length=550, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Área de título',
                'verbose_name_plural': 'Areas de titulos',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(max_length=550, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Mencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(max_length=550, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Mención',
                'verbose_name_plural': 'Menciones',
            },
        ),
        migrations.CreateModel(
            name='TipoTitulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(max_length=550, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de título',
                'verbose_name_plural': 'Tipos ded titulos',
            },
        ),
        migrations.AddField(
            model_name='perfeccionamiento',
            name='es_educacion',
            field=models.BooleanField(default=True, verbose_name='Títulado en educación'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='estado',
            field=models.CharField(choices=[('particular', 'Particular'), ('particular_subvencionado', 'Particular Subvencionado'), ('gratuito', 'Gratuito')], default='particular_subvencionado', max_length=25),
        ),
        migrations.AlterField(
            model_name='documentofuncionario',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.TipoDocumento'),
        ),
        migrations.AlterField(
            model_name='perfeccionamiento',
            name='fecha_titulacion',
            field=models.DateField(verbose_name='Fecha de titulación'),
        ),
        migrations.AlterField(
            model_name='perfeccionamiento',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Nombre del título'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='estado_civil',
            field=models.CharField(choices=[('soltero', 'Soltero'), ('casado', 'Casado'), ('divorsiado', 'Divorsiado'), ('viudo', 'Viudo')], default='soltero', max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='genero',
            field=models.CharField(choices=[('femenino', 'Femenino'), ('masculino', 'Masculino')], default='masculino', max_length=100, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nacionalidad',
            field=models.CharField(choices=[('chilena', 'Chilena'), ('extranjera', 'Extranjera')], default='chilena', max_length=100),
        ),
        migrations.AddField(
            model_name='mencion',
            name='tipo_titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.TipoTitulo', verbose_name='Tipo de título'),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='tipo_titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.TipoTitulo', verbose_name='Tipo de título'),
        ),
        migrations.AddField(
            model_name='perfeccionamiento',
            name='area_titulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.AreaTitulo', verbose_name='Área del título'),
        ),
        migrations.AddField(
            model_name='perfeccionamiento',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.Especialidad'),
        ),
        migrations.AddField(
            model_name='perfeccionamiento',
            name='mencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.Mencion', verbose_name='Mención'),
        ),
    ]
