# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-08-04 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0052_auto_20210803_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegio',
            name='estado',
            field=models.CharField(choices=[('gratuito', 'Gratuito'), ('particular', 'Particular'), ('particular_subvencionado', 'Particular Subvencionado')], default='particular_subvencionado', max_length=25),
        ),
        migrations.AlterField(
            model_name='documentofuncionario',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.TipoDocumento'),
        ),
    ]
