# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-08-17 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0053_auto_20210812_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('conocimiento reglamento', 'Toma de conocimiento del Reglamento Interno'), ('autorizacion diezmo', 'Autorización de descuento de diezmo'), ('autorizacion imagen', 'Autorización de uso de imagen'), ('contrato', 'Contrato'), ('permiso', 'Permiso'), ('licencia', 'Licencia'), ('finiquito', 'Finiquito'), ('perfeccionamiento', 'Perfeccionamiento'), ('otro', 'Otro')], default='otro', max_length=150)),
                ('documento', models.FileField(upload_to='rrhh/documentos')),
                ('fecha_carga', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Docmuento del personal',
                'verbose_name_plural': 'Documentos del personal',
            },
        ),
        migrations.RemoveField(
            model_name='documentofuncionario',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='documentofuncionario',
            name='tipo_documento',
        ),
        migrations.RemoveField(
            model_name='documentopersonal',
            name='contrato',
        ),
        migrations.RemoveField(
            model_name='contratocolegio',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='finiquitocolegio',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='finiquitofundacion',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='finiquitounion',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='perfeccionamiento',
            name='documento_respaldo',
        ),
        migrations.RemoveField(
            model_name='permisofuncionariocolegio',
            name='documento',
        ),
        migrations.AddField(
            model_name='persona',
            name='curriculum',
            field=models.FileField(blank=True, null=True, upload_to='rrhh/curriculums'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='estado',
            field=models.CharField(choices=[('particular_subvencionado', 'Particular Subvencionado'), ('gratuito', 'Gratuito'), ('particular', 'Particular')], default='particular_subvencionado', max_length=25),
        ),
        migrations.DeleteModel(
            name='DocumentoFuncionario',
        ),
        migrations.DeleteModel(
            name='DocumentoPersonal',
        ),
        migrations.AddField(
            model_name='documento',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.ContratoColegio'),
        ),
        migrations.AddField(
            model_name='documento',
            name='finiquito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.FiniquitoColegio'),
        ),
        migrations.AddField(
            model_name='documento',
            name='licencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.LicenciaFuncionarioColegio'),
        ),
        migrations.AddField(
            model_name='documento',
            name='perfeccionamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.Perfeccionamiento'),
        ),
        migrations.AddField(
            model_name='documento',
            name='permiso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.PermisoFuncionarioColegio'),
        ),
    ]
