# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-08-24 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0054_auto_20210817_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'verbose_name': 'Docmuento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AlterField(
            model_name='colegio',
            name='estado',
            field=models.CharField(choices=[('particular', 'Particular'), ('particular_subvencionado', 'Particular Subvencionado'), ('gratuito', 'Gratuito')], default='particular_subvencionado', max_length=25),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo_documento',
            field=models.CharField(choices=[('contrato', 'Contrato'), ('conocimiento reglamento', 'Toma de conocimiento del Reglamento Interno'), ('autorizacion diezmo', 'Autorización de descuento de diezmo'), ('autorizacion imagen', 'Autorización de uso de imagen'), ('permiso', 'Permiso'), ('licencia', 'Licencia'), ('finiquito', 'Finiquito'), ('perfeccionamiento', 'Perfeccionamiento'), ('otro', 'Otro')], default='otro', max_length=150),
        ),
    ]
