# Generated by Django 2.2 on 2021-08-30 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0054_auto_20210817_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'verbose_name': 'Docmuento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AlterField(
            model_name='colegio',
            name='estado',
            field=models.CharField(choices=[('particular', 'Particular'), ('gratuito', 'Gratuito'), ('particular_subvencionado', 'Particular Subvencionado')], default='particular_subvencionado', max_length=50),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo_documento',
            field=models.CharField(choices=[('contrato', 'Contrato'), ('conocimiento reglamento', 'Toma de conocimiento del Reglamento Interno'), ('autorizacion diezmo', 'Autorización de descuento de diezmo'), ('autorizacion imagen', 'Autorización de uso de imagen'), ('permiso', 'Permiso'), ('licencia', 'Licencia'), ('finiquito', 'Finiquito'), ('perfeccionamiento', 'Perfeccionamiento'), ('otro', 'Otro')], default='otro', max_length=150),
        ),
        migrations.AlterField(
            model_name='persona',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
