# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-08-27 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0057_auto_20210827_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegio',
            name='estado',
            field=models.CharField(choices=[('particular', 'Particular'), ('gratuito', 'Gratuito'), ('particular_subvencionado', 'Particular Subvencionado')], default='particular_subvencionado', max_length=25),
        ),
    ]
