# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-08-30 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0059_auto_20210827_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegio',
            name='estado',
            field=models.CharField(choices=[('gratuito', 'Gratuito'), ('particular_subvencionado', 'Particular Subvencionado'), ('particular', 'Particular')], default='particular_subvencionado', max_length=25),
        ),
    ]
