# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-09-08 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0061_auto_20210830_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegio',
            name='estado',
            field=models.CharField(choices=[('particular', 'Particular'), ('gratuito', 'Gratuito'), ('particular_subvencionado', 'Particular Subvencionado')], default='particular_subvencionado', max_length=25),
        ),
    ]
